with Ada.Text_IO; use Ada.Text_IO;
with Interfaces;
with CCL.Periodic_Programs; use CCL.Periodic_Programs;
with CCL.Language;
with CCL.Catalog;
with CCL.Interfaces.Clock;
with Interpreter_Host;

procedure Periodic_Tests is
   use type Timestamp;
   P : Program;
   T, Old, Other : Invocation;
   Loaded_Status : Load_Result;
   Ready, Accepted : Boolean;
   Outcome : CCL.Language.Interpretation_Result :=
     (Status => CCL.Language.Succeeded, others => <>);
   Catalog : CCL.Catalog.Interface_Catalog;
   Grants, Missing : CCL.Catalog.Granted_Bindings;
   Operation : CCL.Catalog.Resolved_Operation;
   Error : CCL.Catalog.Catalog_Error;
   Grant : CCL.Catalog.Grant_Result;
   Host : Interpreter_Host.State;
   procedure Pump
     (Item : in out Program; Catalog : CCL.Catalog.Interface_Catalog;
      Grants : CCL.Catalog.Granted_Bindings; Context : in out Interpreter_Host.State;
      Updated : out Boolean) renames Interpreter_Host.Pump;
   use type CCL.Catalog.Catalog_Error;
   use type CCL.Catalog.Grant_Result;
   use type CCL.Language.Interpretation_Status;
   use type Interfaces.Unsigned_32;
begin
   pragma Assert (State (P) = Empty);
   Claim_Due (P, 0, T, Ready); pragma Assert (not Ready);
   Load (P, "(clock.monotonic-ms)", 100, 1000, 4096, Loaded_Status);
   pragma Assert (Loaded_Status = Loaded and State (P) = Waiting);
   pragma Assert (Source_Text (P) = "(clock.monotonic-ms)");
   Load (P, "7", 100, 1000, 4096, Loaded_Status);
   pragma Assert (Loaded_Status = Busy and Source_Text (P) = "(clock.monotonic-ms)");
   Claim_Due (P, 99, T, Ready); pragma Assert (not Ready);
   Claim_Due (P, 100, T, Ready); pragma Assert (Ready and State (P) = Executing);
   Claim_Due (P, 101, Other, Ready); pragma Assert (not Ready);
   Complete (P, Other, 102, Outcome, Accepted); pragma Assert (not Accepted);
   Complete (P, T, 105, Outcome, Accepted);
   pragma Assert (Accepted and Next_Deadline (P) = 1105 and Completed_Runs (P) = 1);
   Complete (P, T, 106, Outcome, Accepted); pragma Assert (not Accepted);
   Old := T;
   Claim_Due (P, 9000, T, Ready); pragma Assert (Ready);
   Complete (P, Old, 9001, Outcome, Accepted); pragma Assert (not Accepted);
   Complete (P, T, 9010, Outcome, Accepted);
   pragma Assert (Accepted and Next_Deadline (P) = 10010 and Completed_Runs (P) = 2);
   Claim_Due (P, 9011, T, Ready); pragma Assert (not Ready);
   Stop (P); pragma Assert (State (P) = Stopped);
   Load (P, [1 .. CCL.Language.MAX_SOURCE_LENGTH + 1 => 'x'], 20000, 1000, 64, Loaded_Status);
   pragma Assert (Loaded_Status = Source_Too_Long and State (P) = Stopped);
   pragma Assert (Source_Text (P) = "(clock.monotonic-ms)");
   Claim_Due (P, 20000, T, Ready); pragma Assert (not Ready);
   Load (P, "8", 20000, 1000, 64, Loaded_Status);
   Claim_Due (P, 20000, T, Ready); pragma Assert (Ready and Fuel (P) = 64);
   Complete (P, Old, 20001, Outcome, Accepted); pragma Assert (not Accepted);
   Stop (P); pragma Assert (State (P) = Stopping);
   Load (P, "9", 20002, 1000, 64, Loaded_Status); pragma Assert (Loaded_Status = Busy);
   Complete (P, T, 20010, Outcome, Accepted);
   pragma Assert (Accepted and State (P) = Stopped);
   Load (P, "bad", 30000, 1000, 64, Loaded_Status);
   Claim_Due (P, 30000, T, Ready); pragma Assert (Ready);
   Outcome.Status := CCL.Language.Host_Authority_Denied;
   Complete (P, T, 30010, Outcome, Accepted);
   pragma Assert (Accepted and State (P) = Faulted);
   Claim_Due (P, 40000, T, Ready); pragma Assert (not Ready);
   Load (P, "10", Timestamp'Last - 1, 1000, 64, Loaded_Status);
   Claim_Due (P, Timestamp'Last - 1, T, Ready); pragma Assert (Ready);
   Outcome.Status := CCL.Language.Succeeded;
   Complete (P, T, Timestamp'Last, Outcome, Accepted);
   pragma Assert (Accepted and State (P) = Faulted);
   Put_Line ("PASS: periodic lifecycle, deadlines, coalescing, stop, stale completions and failure isolation");

   CCL.Catalog.Initialize (Catalog);
   CCL.Catalog.Initialize (Grants);
   CCL.Catalog.Initialize (Missing);
   CCL.Interfaces.Clock.Publish (Catalog, Error);
   pragma Assert (Error = CCL.Catalog.Catalog_Valid);
   CCL.Interfaces.Clock.Resolve_Monotonic_Ms (Catalog, Operation, Ready);
   pragma Assert (Ready);
   CCL.Catalog.Install (Grants, Operation, 77, Grant);
   pragma Assert (Grant = CCL.Catalog.Grant_Added);
   Load (P, "(to-string (clock.monotonic-ms))", 0, 1000, 4096, Loaded_Status);
   Pump (P, Catalog, Missing, Host, Accepted);
   pragma Assert (Accepted and State (P) = Faulted and Host.Calls = 0);
   pragma Assert (Last_Result (P).Status = CCL.Language.Host_Authority_Denied);
   Load (P, "(to-string (clock.monotonic-ms))", 0, 1000, 4096, Loaded_Status);
   Pump (P, Catalog, Grants, Host, Accepted);
   pragma Assert (Accepted and Host.Calls = 1 and Last_Result (P).Has_Text);
   pragma Assert (Last_Result (P).Result_Text.Data (1 .. 7) = "3661000");
   Host.Tick := 999;
   Pump (P, Catalog, Grants, Host, Accepted);
   pragma Assert (not Accepted and Host.Calls = 1);
   Host.Tick := 5000; -- missed samples coalesce to one invocation
   Pump (P, Catalog, Grants, Host, Accepted);
   pragma Assert (Accepted and Host.Calls = 2 and Next_Deadline (P) = 6000);
   Stop (P);
   Host.Tick := 6000;
   Pump (P, Catalog, Grants, Host, Accepted);
   pragma Assert (not Accepted and Host.Calls = 2);
   Load (P, "(+ 1 (clock.monotonic-ms))", Host.Tick, 1000, 1, Loaded_Status);
   Pump (P, Catalog, Grants, Host, Accepted);
   pragma Assert (Accepted and State (P) = Faulted);
   pragma Assert (Last_Result (P).Status = CCL.Language.Evaluation_Fuel_Exhausted and Host.Calls = 2);
   Put_Line ("PASS: live label host binding, string result, fuel, coalescing and stopped-call isolation");
end Periodic_Tests;
