package body CCL.Hints with SPARK_Mode is
   function Hint (Name : String) return String is
     (if Name = "each" then "(each f xs) : (a -> b) (List a) -> (List b)  apply f to every element"
      elsif Name = "where" then "(where p xs) : (a -> Boolean) (List a) -> (List a)  keep elements where p holds"
      elsif Name = "fold" then "(fold f init xs) : (b a -> b) b (List a) -> b  combine elements left to right"
      elsif Name = "any" then "(any p xs) : (a -> Boolean) (List a) -> Boolean  true if p holds for some element"
      elsif Name = "all" then "(all p xs) : (a -> Boolean) (List a) -> Boolean  true if p holds for every element"
      elsif Name = "count" then "(count p xs) : (a -> Boolean) (List a) -> Integer  how many elements satisfy p"
      elsif Name = "first" then "(first n xs) : Integer (List a) -> (List a)  the first n elements (or characters)"
      elsif Name = "last" then "(last n xs) : Integer (List a) -> (List a)  the last n elements (or characters)"
      elsif Name = "skip" then "(skip n xs) : Integer (List a) -> (List a)  all but the first n"
      elsif Name = "reverse" then "(reverse xs) : (List a) -> (List a)  the elements in reverse order"
      elsif Name = "sort" then "(sort xs) : (List a) -> (List a)  ascending; a is Integer, String, Character or enum"
      elsif Name = "sort-by" then "(sort-by key xs) : (a -> Integer|String) (List a) -> (List a)  ascending by key"
      elsif Name = "sum" then "(sum xs) : (List Integer) -> Integer  the total"
      elsif Name = "min" then "(min xs) : (List Integer) -> Integer  the smallest element"
      elsif Name = "max" then "(max xs) : (List Integer) -> Integer  the largest element"
      elsif Name = "contains" then "(contains x xs) : a (List a) -> Boolean  whether xs has x (or a String has a part)"
      elsif Name = "range" then "(range from to) : Integer Integer -> (List Integer)  from, from+1, ..., to"
      elsif Name = "upper" then "(upper s) : String -> String  in upper case"
      elsif Name = "lower" then "(lower s) : String -> String  in lower case"
      elsif Name = "trim" then "(trim s) : String -> String  without leading and trailing spaces"
      elsif Name = "starts-with" then "(starts-with prefix s) : String String -> Boolean"
      elsif Name = "ends-with" then "(ends-with suffix s) : String String -> Boolean"
      elsif Name = "index-of" then "(index-of part s) : String String -> Integer  where part starts (from 1), 0 if absent"
      elsif Name = "replace" then "(replace old new s) : String String String -> String  every occurrence"
      elsif Name = "split" then "(split separator s) : String String -> (List String)"
      elsif Name = "join" then "(join separator parts) : String (List String) -> String"
      elsif Name = "parse-int" then "(parse-int s) : String -> Integer  a decimal integer"
      elsif Name = "latest" then "(latest s) : (Stream a) -> a  the newest element; waits for the first"
      elsif Name = "window" then "(window n s) : Integer (Stream a) -> (List a)  up to the n newest elements"
      elsif Name = "arrived" then "(arrived s) : (Stream a) -> Integer  how many elements have arrived"
      elsif Name = "lost" then "(lost s) : (Stream a) -> Integer  how many fell out of the history"
      elsif Name = "wait" then "(wait t) : (Task a) -> a  the task's result, once it completes"
      elsif Name = "define" then "(define (f (x T) ...) R body)  a function; visible after its own body"
      elsif Name = "type" then "(type N (record (f T [default]) ...) | (enum A ...) | (variant (A [T]) ...) | (range lo hi))"
      elsif Name = "let" then "(let ((x e) ...) body)  name values for body"
      elsif Name = "if" then "(if c then else) : Boolean a a -> a"
      elsif Name = "match" then "(match v ((T.A x) e) ...)  one arm per alternative, all of them"
      elsif Name = "fn" then "(fn ((x T) ...) body)  a function value; captures only plain data"
      elsif Name = "handler" then "(handler f)  a callback to a 0-argument Boolean function"
      elsif Name = "field" then "(field r f) : R -> T  the field f of record r"
      elsif Name = "list" then "(list e ...) or [e ...] : a ... -> (List a)"
      elsif Name = "list-of" then "(list-of T) : (List T)  the empty list of T"
      elsif Name = "stream" then "(stream T n) : (Stream T)  stream n of this session"
      elsif Name = "->>" then "(->> x (f a) ...)  thread x as the last argument of each step"
      elsif Name in "and" | "or" then "(" & Name & " a b ...) : Boolean ... -> Boolean"
      elsif Name = "not" then "(not b) : Boolean -> Boolean"
      elsif Name in "+" | "-" | "*" | "/" | "%" | "add" | "subtract" | "multiply" | "divide" | "mod" | "modulo"
      then "(" & Name & " a b) : Integer Integer -> Integer"
      elsif Name in "<" | "<=" | ">" | ">=" | "less" | "less-equal" | "greater" | "greater-equal"
      then "(" & Name & " a b) : a a -> Boolean  a is Integer, String, Character or enum"
      elsif Name in "=" | "/=" | "equal" | "not-equal" then "(" & Name & " a b) : a a -> Boolean"
      elsif Name = "at" then "(at xs i) : (List a) Integer -> a  element i, from 1 (a Character of a String)"
      elsif Name = "concat" then "(concat a b) : String String -> String"
      elsif Name = "length" then "(length xs) : (List a) -> Integer  (or the length of a String)"
      elsif Name = "to-string" then "(to-string x) : Integer|enum -> String"
      else "");
end CCL.Hints;
