with Ada.Text_IO;
with Interfaces; use Interfaces;
with CuBit.Messages;
with CuBit.Memory_Grants;
with Native_GPU_Buffers;
with Native_GPU_Memory;
with Intel_GPU_Buffer_Backing;
procedure Composed_Tests is
   package Client renames Native_GPU_Buffers;
   package G renames CuBit.Memory_Grants;
   ID, Mapping : aliased Unsigned_32 := 0;
   Reference : aliased Unsigned_64 := 0;
   Address : aliased Unsigned_64 := 0;
   Status : Unsigned_32;
   Before : Natural;
   function Test_C_Mapping (Handle : Unsigned_32) return Unsigned_32
     with Import, Convention => C, External_Name => "test_composed_mapping_c";
begin
   Status := Client.Create (63, 8192, ID'Access);
   pragma Assert (Status = 0 and ID /= 0);
   G.Expected_Slot := 7;
   G.Expected_Offset := Intel_GPU_Buffer_Backing.CPU_Base + 4096;
   G.Expected_Bytes := 4096;
   G.Expected_Reference := (slot => 8, generation => 9);
   G.Expected_Access := G.Write_Access;
   Status := Client.Map (62, ID, 4096, 4096, 1, Mapping'Access, Reference'Access);
   pragma Assert (Status = 1 and Mapping = 0 and Reference = 0 and G.Creates = 0);
   Status := Client.Map (63, ID, 4096, 4096, 1, Mapping'Access, Reference'Access);
   pragma Assert (Status = 0 and Mapping /= 0 and Reference = 9 * 2 ** 32 + 8);
   -- The grant exposes only the requested subrange: its acquisition offset
   -- is zero, not the original BO offset and never a driver CPU address.
   G.Expected_Slot := 63;
   G.Expected_Offset := 0;
   Status := Native_GPU_Memory.Acquire (63, Reference, 0, 4096, 1, Address'Access);
   pragma Assert (Status = 0 and Address /= 0 and G.Calls = 1);
   Status := Native_GPU_Memory.Return_Borrow (Reference);
   pragma Assert (Status = 0 and G.Returns = 1);
   G.Expected_Slot := 7;
   G.Expected_Offset := Intel_GPU_Buffer_Backing.CPU_Base + 4096;
   Status := Client.Retire_Map (62, Mapping);
   pragma Assert (Status = 1 and G.Revokes = 0);
   Status := Client.Retire_Map (63, Mapping);
   pragma Assert (Status = 4 and G.Revokes = 1);
   Status := Client.Retire_Map (63, Mapping);
   pragma Assert (Status = 4 and G.Revokes = 1);
   G.Gone := True;
   Status := Client.Retire_Map (63, Mapping);
   pragma Assert (Status = 0 and G.Revokes = 1);
   G.Expected_Reference := (slot => 8, generation => 10);
   CuBit.Messages.Recipient_Generation := 8;
   Before := G.Creates;
   Status := Client.Map (63, ID, 4096, 4096, 1, Mapping'Access, Reference'Access);
   pragma Assert (Status = 3 and Mapping = 0 and Reference = 0 and G.Creates = Before);
   CuBit.Messages.Recipient_Generation := 7;
   CuBit.Messages.Fail_Delivery := True;
   Status := Client.Map (63, ID, 4096, 4096, 1, Mapping'Access, Reference'Access);
   pragma Assert (Status = 5 and Mapping = 0 and Reference = 0 and G.Revokes = 2);
   CuBit.Messages.Fail_Delivery := False;
   G.Separate_Create_Expectations := True;
   G.Create_Slot := 7;
   G.Create_Offset := Intel_GPU_Buffer_Backing.CPU_Base + 4096;
   G.Expected_Slot := 63;
   G.Expected_Offset := 0;
   G.Expected_Reference := (slot => 8, generation => 11);
   pragma Assert (Test_C_Mapping (ID) = 0);
   Status := Client.Close (63, ID);
   pragma Assert (Status = 0);
   Before := G.Creates;
   Status := Client.Map (63, ID, 4096, 4096, 1, Mapping'Access, Reference'Access);
   pragma Assert (Status = 3 and Mapping = 0 and Reference = 0 and G.Creates = Before);
   Ada.Text_IO.Put_Line ("Composed GPU create/map/acquire/return/retire/close PASS; mock IPC and kernel grants only");
end Composed_Tests;
