with Ada.Text_IO;
with Interfaces; use Interfaces;
with CCL.Types;
with CCL.Objects;
with Config_Authority;
with Config_Collections;
with Config_Objects;
with Config_Worker_Protocol;
with Config_Typed_Store; use Config_Typed_Store;

procedure Typed_Store_Tests is
   package A renames Config_Authority;
   package C renames Config_Collections;
   package V renames Config_Objects;
   package P renames Config_Worker_Protocol;
   use type A.Install_Result;
   use type C.Result;
   use type C.Collection_ID;
   use type V.Outcome;
   use type V.Read_Result;
   use type CCL.Objects.Image;
   use type CCL.Objects.Build_Result;
   Store : State;
   Authority : A.Authority_State;
   Rules : A.Rule_Set;
   Types : CCL.Types.Registry;
   Contract, Retrieved : CCL.Objects.Binding;
   Schema : constant CCL.Objects.Schema_Key := [1, 2, 3, 4];
   First, Second, Actual, Invalid : CCL.Objects.Image;
   ID, Other_ID : C.Collection_ID;
   Writer, Reader : C.Handle;
   Access_Result : C.Result;
   Result : V.Outcome;
   Installed : A.Install_Result;
   Built : CCL.Objects.Build_Result;
   Revision : Number;
   Read_Result : V.Read_Result;
   Authorized, Good, Available : Boolean;
   Request, Response, Saved : P.Frame;
   Checks : Natural := 0;
   procedure Check (OK : Boolean) is
   begin
      Checks := Checks + 1;
      if not OK then raise Program_Error with "typed store check" & Checks'Image; end if;
   end Check;
   procedure Read_Check (Expected : V.Read_Result; Rev : Number; Value : CCL.Objects.Image) is
   begin
      Get (Store, Authority, 42, Reader, Actual, Revision, Authorized, Read_Result);
      Check (Authorized and Read_Result = Expected and Revision = Rev);
      Check (Actual = (if Expected in V.Found | V.Stale then Value else (others => <>)));
   end Read_Check;
   procedure Finish (Kind : P.Reply_Kind; Rev : Number; Value : CCL.Objects.Image) is
   begin
      Pending (Store, Request, Retrieved, Available); Check (Available);
      Check (Request.Name (1 .. Natural (Request.Name_Length)) = "org.cubit.settings");
      Check (Request.Context (1 .. Natural (Request.Context_Length)) = "machine");
      P.Make_Reply (Request, Kind, Rev, Retrieved, Value, Response, Good); Check (Good);
      Complete (Store, Response, Result);
   end Finish;
begin
   CCL.Objects.Bind (Types, CCL.Types.Integer_Type, Schema, Contract, Good); Check (Good);
   First := CCL.Objects.Empty (Contract); Second := First;
   CCL.Objects.Append (First, CCL.Objects.Integer_Cell (41), Built); Check (Built = CCL.Objects.Added);
   CCL.Objects.Append (Second, CCL.Objects.Integer_Cell (42), Built); Check (Built = CCL.Objects.Added);
   Invalid := First; Invalid.Reserved := 1;
   Register (Store, "org.cubit.settings", Contract, ID, Access_Result); Check (Access_Result = C.Registered);
   Register (Store, "org.cubit.other", Contract, Other_ID, Access_Result); Check (Access_Result = C.Registered);
   A.Append (Rules, "org.cubit", A.Read_Write, Good); Check (Good);
   A.Install (Authority, 42, Rules, Installed); Check (Installed = A.Installed);
   Open (Store, Authority, 42, "org.cubit.settings", 0, A.Read_Write, Schema, Writer, Access_Result);
   Check (Access_Result = C.Opened);
   Open (Store, Authority, 42, "org.cubit.settings", 0, A.Read_Only, Schema, Reader, Access_Result);
   Check (Access_Result = C.Opened);
   Read_Check (V.Unavailable, 0, First);
   Set (Store, Authority, 42, Writer, First, 0, 1, Authorized, Result);
   Check (Authorized and Result = V.Needs_Recovery);
   Restore (Store, ID, 10, 2, Result); Check (Result = V.Accepted);
   Restore (Store, Other_ID, 10, 3, Result); Check (Result = V.Busy);
   Finish (P.Absent, 0, First); Check (Result = V.Accepted);
   Read_Check (V.Missing, 0, First);
   Set (Store, Authority, 99, Writer, First, 0, 3, Authorized, Result);
   Check (not Authorized and Result = V.Rejected);
   Set (Store, Authority, 42, Reader, First, 0, 3, Authorized, Result);
   Check (not Authorized and Result = V.Rejected);
   Pending (Store, Request, Retrieved, Available); Check (not Available);
   Set (Store, Authority, 42, Writer, Invalid, 0, 3, Authorized, Result);
   Check (Authorized and Result = V.Invalid_Value);
   Set (Store, Authority, 42, Writer, First, 0, 3, Authorized, Result);
   Check (Authorized and Result = V.Invalid_Request);
   Set (Store, Authority, 42, Writer, First, 0, 4, Authorized, Result);
   Check (Authorized and Result = V.Accepted);
   Read_Check (V.Missing, 0, First);
   Set (Store, Authority, 42, Writer, Second, 0, 5, Authorized, Result);
   Check (Authorized and Result = V.Busy);
   Pending (Store, Request, Retrieved, Available); Check (Available and Request.Value = First);
   Saved := Request;
   P.Make_Reply (Request, P.Committed, 1, Retrieved, First, Response, Good); Check (Good);
   Response.Token := 999;
   Complete (Store, Response, Result); Check (Result = V.Ignored);
   Read_Check (V.Missing, 0, First);
   Finish (P.Committed, 1, First); Check (Result = V.Published);
   Read_Check (V.Found, 1, First);
   Complete (Store, Response, Result); Check (Result = V.Ignored);
   Set (Store, Authority, 42, Writer, Second, 0, 5, Authorized, Result);
   Check (Authorized and Result = V.Revision_Conflict);
   Set (Store, Authority, 42, Writer, Second, 1, 6, Authorized, Result);
   Check (Authorized and Result = V.Accepted);
   Read_Check (V.Found, 1, First);
   --  Revocation after acceptance prevents subsequent reads/writes. It cannot
   --  undo a database commit that may already have happened.
   A.Revoke (Authority, 42);
   Get (Store, Authority, 42, Reader, Actual, Revision, Authorized, Read_Result);
   Check (not Authorized and Revision = 0 and Actual = CCL.Objects.Image'(others => <>));
   Finish (P.Committed, 2, Second); Check (Result = V.Published);
   A.Install (Authority, 42, Rules, Installed); Check (Installed = A.Installed);
   Get (Store, Authority, 42, Reader, Actual, Revision, Authorized, Read_Result); Check (not Authorized);
   Revoke_Subject (Store, 42);
   Open (Store, Authority, 42, "org.cubit.settings", 0, A.Read_Write, Schema, Writer, Access_Result);
   Check (Access_Result = C.Opened);
   Reader := Writer;
   Read_Check (V.Found, 2, Second);
   Set (Store, Authority, 42, Writer, First, 2, 7, Authorized, Result); Check (Result = V.Accepted);
   Worker_Lost (Store, 9); Read_Check (V.Found, 2, Second);
   Worker_Lost (Store, 10); Read_Check (V.Stale, 2, Second);
   Complete (Store, Response, Result); Check (Result = V.Ignored);
   Set (Store, Authority, 42, Writer, First, 2, 8, Authorized, Result); Check (Result = V.Needs_Recovery);
   Restore (Store, ID, 11, 9, Result); Check (Result = V.Accepted);
   Finish (P.Loaded, 2, Second); Check (Result = V.Published);
   Read_Check (V.Found, 2, Second);
   Set (Store, Authority, 42, Writer, First, 2, 10, Authorized, Result); Check (Result = V.Accepted);
   Finish (P.Rejected, 2, First); Check (Result = V.Rejected);
   Read_Check (V.Found, 2, Second);
   Set (Store, Authority, 42, Writer, First, 2, 11, Authorized, Result); Check (Result = V.Accepted);
   Pending (Store, Request, Retrieved, Available); Check (Available);
   P.Make_Reply (Request, P.Committed, 3, Retrieved, First, Response, Good); Check (Good);
   Response.Padding (1) := 1;
   Complete (Store, Response, Result); Check (Result = V.Needs_Recovery);
   Read_Check (V.Stale, 2, Second);
   Restore (Store, ID, 12, 12, Result); Check (Result = V.Accepted);
   Finish (P.Loaded, 3, First); Check (Result = V.Published);
   Read_Check (V.Found, 3, First);
   Close (Store, 42, Writer, Access_Result); Check (Access_Result = C.Closed);
   Get (Store, Authority, 42, Writer, Actual, Revision, Authorized, Read_Result); Check (not Authorized);
   Ada.Text_IO.Put_Line ("Authorized typed Config publication: PASS" & Checks'Image & " checks");
end Typed_Store_Tests;
