[package]
name = "cubit-turso-native-probe"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[lib]
crate-type = ["staticlib"]

[features]
turso = ["dep:turso_core", "dep:config-storage"]

[dependencies]
config-storage = { package = "cubit-config-turso-spike", path = "..", optional = true }
cubit = { path = "../../../userspace/rust/cubit" }
cubit-allocator = { path = "../../../userspace/rust/allocator" }
getrandom02 = { package = "getrandom", version = "=0.2.17", features = ["rdrand"] }
getrandom = "=0.3.4"
turso_core = { version = "=0.8.0-pre.12", optional = true, default-features = false, features = ["fs", "uuid", "json", "pure-rust-crypto"] }

[patch.crates-io]
turso_core = { path = "../target/native-turso" }

[profile.release]
panic = "abort"
opt-level = 2
overflow-checks = true
debug = 1

[profile.dev]
panic = "abort"
