with CCL_Workspace_Names;
--  Linux-only deterministic, process-local mock. Never opens host files.
package body CCL_Workspace is
   use CCL_Workspace_Names;
   use CuBit.File_Selection;
   Names : File_List;
   type Sources is array (Positive range 1 .. Maximum_Files) of Source_Buffer;
   type Lengths is array (Positive range 1 .. Maximum_Files) of Source_Length;
   Data : Sources := [others => [others => ' ']];
   Sizes : Lengths := [others => 0];
   Initialized : Boolean := False;

   function Supported return Boolean is (True);
   function Location return String is ("Linux mock workspace (memory only)");
   procedure Shutdown is null;

   function Valid_Text (Text : String) return Boolean is
     (Text'Length <= Maximum_Source_Bytes and then
      (for all C of Text => C in ' ' .. '~' | ASCII.LF | ASCII.CR | ASCII.HT));

   procedure Initialize is
      Accepted : Boolean;
      Hello : constant String := "# Mock workspace: no host files are accessed." & ASCII.LF & "(+ 20 22)";
      Arithmetic : constant String := "(let ((minutes (/ 3661 60))) minutes)";
   begin
      if Initialized then return; end if;
      Append (Names, "hello.ccl", Accepted);
      Data (1) (1 .. Hello'Length) := Hello;
      Sizes (1) := Hello'Length;
      Append (Names, "arithmetic.ccl", Accepted);
      Data (2) (1 .. Arithmetic'Length) := Arithmetic;
      Sizes (2) := Arithmetic'Length;
      Initialized := True;
   end Initialize;

   procedure List_Files (Files : out File_List; Result : out Storage_Result) is
   begin
      Initialize;
      Files := Names;
      Result := Succeeded;
   end List_Files;

   procedure Load
     (Name : String; Text : out Source_Buffer; Length : out Source_Length;
      Result : out Storage_Result)
   is
   begin
      Text := [others => ' '];
      Length := 0;
      Result := Invalid_Name;
      if not Valid_Source_Name (Name) then return; end if;
      Initialize;
      for Index in 1 .. Names.Count loop
         if Value (Names.Names (Index)) = Name then
            Text := Data (Index);
            Length := Sizes (Index);
            Result := Succeeded;
            return;
         end if;
      end loop;
      Result := Not_Found;
   end Load;

   procedure Save_New (Name, Text : String; Result : out Storage_Result) is
      Accepted : Boolean;
   begin
      Result := Invalid_Name;
      if not Valid_Source_Name (Name) then return; end if;
      Result := Invalid_Source;
      if not Valid_Text (Text) then return; end if;
      Initialize;
      for Item in 1 .. Names.Count loop
         if Value (Names.Names (Item)) = Name then
            Result := Conflict;
            return;
         end if;
      end loop;
      Append (Names, Name, Accepted);
      if not Accepted then
         Result := Limit_Reached;
         return;
      end if;
      Data (Names.Count) (1 .. Text'Length) := Text;
      Sizes (Names.Count) := Text'Length;
      Result := Succeeded;
   end Save_New;

   procedure Scan (Latest : out Revision) is
      Number : Revision;
      Pending : Boolean;
   begin
      Initialize;
      Latest := 0;
      for Index in 1 .. Names.Count loop
         Decode (Value (Names.Names (Index)), Number, Pending);
         if not Pending then Latest := Revision'Max (Latest, Number); end if;
      end loop;
   end Scan;

   procedure Suggest_Name (Name : out File_Name; Result : out Storage_Result) is
      Latest : Revision;
      Accepted : Boolean;
   begin
      Name := (others => <>);
      Scan (Latest);
      if Latest = Revision'Last then
         Result := Limit_Reached;
      else
         Set (Name, Filename (Latest + 1, False), Accepted);
         Result := (if Accepted then Succeeded else Invalid_Name);
      end if;
   end Suggest_Name;

   --  Demo pictures for image.load: generated bytes, not host files.
   type Byte_String is array (Positive range <>) of Natural range 0 .. 255;
DEMO_QOI : constant Byte_String := 
     [113, 111, 105, 102, 0, 0, 0, 24, 0, 0, 0, 16, 3, 0, 254, 40, 60, 200, 254, 49,
      60, 195, 254, 58, 60, 190, 254, 67, 60, 185, 254, 76, 60, 180, 254, 85, 60, 175, 254, 94,
      60, 170, 254, 103, 60, 165, 254, 112, 60, 160, 254, 121, 60, 155, 254, 130, 60, 150, 254, 139,
      60, 145, 254, 148, 60, 140, 254, 157, 60, 135, 254, 166, 60, 130, 254, 175, 60, 125, 254, 184,
      60, 120, 254, 193, 60, 115, 254, 202, 60, 110, 254, 211, 60, 105, 254, 220, 60, 100, 254, 229,
      60, 95, 254, 238, 60, 90, 254, 247, 60, 85, 254, 40, 70, 200, 254, 49, 70, 195, 254, 58,
      70, 190, 254, 67, 70, 185, 254, 76, 70, 180, 254, 85, 70, 175, 254, 94, 70, 170, 254, 103,
      70, 165, 254, 112, 70, 160, 254, 121, 70, 155, 254, 130, 70, 150, 254, 139, 70, 145, 254, 148,
      70, 140, 254, 157, 70, 135, 254, 166, 70, 130, 254, 175, 70, 125, 254, 184, 70, 120, 254, 193,
      70, 115, 254, 202, 70, 110, 254, 211, 70, 105, 254, 220, 70, 100, 254, 229, 70, 95, 254, 238,
      70, 90, 254, 247, 70, 85, 254, 40, 80, 200, 254, 49, 80, 195, 254, 58, 80, 190, 254, 67,
      80, 185, 254, 76, 80, 180, 254, 85, 80, 175, 254, 94, 80, 170, 254, 103, 80, 165, 254, 112,
      80, 160, 254, 121, 80, 155, 254, 130, 80, 150, 254, 139, 80, 145, 254, 148, 80, 140, 254, 157,
      80, 135, 254, 166, 80, 130, 254, 175, 80, 125, 254, 184, 80, 120, 254, 193, 80, 115, 254, 202,
      80, 110, 254, 211, 80, 105, 254, 220, 80, 100, 254, 229, 80, 95, 254, 238, 80, 90, 254, 247,
      80, 85, 254, 40, 90, 200, 254, 49, 90, 195, 254, 58, 90, 190, 254, 67, 90, 185, 254, 76,
      90, 180, 254, 85, 90, 175, 254, 94, 90, 170, 254, 103, 90, 165, 254, 112, 90, 160, 254, 121,
      90, 155, 254, 130, 90, 150, 254, 139, 90, 145, 254, 148, 90, 140, 254, 157, 90, 135, 254, 166,
      90, 130, 254, 175, 90, 125, 254, 184, 90, 120, 254, 193, 90, 115, 254, 202, 90, 110, 254, 211,
      90, 105, 254, 220, 90, 100, 254, 229, 90, 95, 254, 238, 90, 90, 254, 247, 90, 85, 254, 40,
      100, 200, 254, 49, 100, 195, 254, 58, 100, 190, 254, 67, 100, 185, 254, 76, 100, 180, 254, 85,
      100, 175, 254, 94, 100, 170, 254, 103, 100, 165, 254, 112, 100, 160, 254, 121, 100, 155, 254, 255,
      204, 102, 195, 254, 175, 100, 125, 254, 184, 100, 120, 254, 193, 100, 115, 254, 202, 100, 110, 254,
      211, 100, 105, 254, 220, 100, 100, 254, 229, 100, 95, 254, 238, 100, 90, 254, 247, 100, 85, 254,
      40, 110, 200, 254, 49, 110, 195, 254, 58, 110, 190, 254, 67, 110, 185, 254, 76, 110, 180, 254,
      85, 110, 175, 254, 94, 110, 170, 254, 103, 110, 165, 254, 112, 110, 160, 254, 255, 204, 102, 197,
      254, 184, 110, 120, 254, 193, 110, 115, 254, 202, 110, 110, 254, 211, 110, 105, 254, 220, 110, 100,
      254, 229, 110, 95, 254, 238, 110, 90, 254, 247, 110, 85, 254, 40, 120, 200, 254, 49, 120, 195,
      254, 58, 120, 190, 254, 67, 120, 185, 254, 76, 120, 180, 254, 85, 120, 175, 254, 94, 120, 170,
      254, 103, 120, 165, 254, 255, 204, 102, 199, 254, 193, 120, 115, 254, 202, 120, 110, 254, 211, 120,
      105, 254, 220, 120, 100, 254, 229, 120, 95, 254, 238, 120, 90, 254, 247, 120, 85, 254, 40, 130,
      200, 254, 49, 130, 195, 254, 58, 130, 190, 254, 67, 130, 185, 254, 76, 130, 180, 254, 85, 130,
      175, 254, 94, 130, 170, 254, 103, 130, 165, 254, 255, 204, 102, 199, 254, 193, 130, 115, 254, 202,
      130, 110, 254, 211, 130, 105, 254, 220, 130, 100, 254, 229, 130, 95, 254, 238, 130, 90, 254, 247,
      130, 85, 254, 40, 140, 200, 254, 49, 140, 195, 254, 58, 140, 190, 254, 67, 140, 185, 254, 76,
      140, 180, 254, 85, 140, 175, 254, 94, 140, 170, 254, 103, 140, 165, 254, 255, 204, 102, 199, 254,
      193, 140, 115, 254, 202, 140, 110, 254, 211, 140, 105, 254, 220, 140, 100, 254, 229, 140, 95, 254,
      238, 140, 90, 254, 247, 140, 85, 254, 40, 150, 200, 254, 49, 150, 195, 254, 58, 150, 190, 254,
      67, 150, 185, 254, 76, 150, 180, 254, 85, 150, 175, 254, 94, 150, 170, 254, 103, 150, 165, 254,
      255, 204, 102, 199, 254, 193, 150, 115, 254, 202, 150, 110, 254, 211, 150, 105, 254, 220, 150, 100,
      254, 229, 150, 95, 254, 238, 150, 90, 254, 247, 150, 85, 254, 40, 160, 200, 254, 49, 160, 195,
      254, 58, 160, 190, 254, 67, 160, 185, 254, 76, 160, 180, 254, 85, 160, 175, 254, 94, 160, 170,
      254, 103, 160, 165, 254, 255, 204, 102, 199, 254, 193, 160, 115, 254, 202, 160, 110, 254, 211, 160,
      105, 254, 220, 160, 100, 254, 229, 160, 95, 254, 238, 160, 90, 254, 247, 160, 85, 254, 40, 170,
      200, 254, 49, 170, 195, 254, 58, 170, 190, 254, 67, 170, 185, 254, 76, 170, 180, 254, 85, 170,
      175, 254, 94, 170, 170, 254, 103, 170, 165, 254, 112, 170, 160, 254, 255, 204, 102, 197, 254, 184,
      170, 120, 254, 193, 170, 115, 254, 202, 170, 110, 254, 211, 170, 105, 254, 220, 170, 100, 254, 229,
      170, 95, 254, 238, 170, 90, 254, 247, 170, 85, 254, 40, 180, 200, 254, 49, 180, 195, 254, 58,
      180, 190, 254, 67, 180, 185, 254, 76, 180, 180, 254, 85, 180, 175, 254, 94, 180, 170, 254, 103,
      180, 165, 254, 112, 180, 160, 254, 121, 180, 155, 254, 255, 204, 102, 195, 254, 175, 180, 125, 254,
      184, 180, 120, 254, 193, 180, 115, 254, 202, 180, 110, 254, 211, 180, 105, 254, 220, 180, 100, 254,
      229, 180, 95, 254, 238, 180, 90, 254, 247, 180, 85, 254, 40, 190, 200, 254, 49, 190, 195, 254,
      58, 190, 190, 254, 67, 190, 185, 254, 76, 190, 180, 254, 85, 190, 175, 254, 94, 190, 170, 254,
      103, 190, 165, 254, 112, 190, 160, 254, 121, 190, 155, 254, 130, 190, 150, 254, 139, 190, 145, 254,
      148, 190, 140, 254, 157, 190, 135, 254, 166, 190, 130, 254, 175, 190, 125, 254, 184, 190, 120, 254,
      193, 190, 115, 254, 202, 190, 110, 254, 211, 190, 105, 254, 220, 190, 100, 254, 229, 190, 95, 254,
      238, 190, 90, 254, 247, 190, 85, 254, 40, 200, 200, 254, 49, 200, 195, 254, 58, 200, 190, 254,
      67, 200, 185, 254, 76, 200, 180, 254, 85, 200, 175, 254, 94, 200, 170, 254, 103, 200, 165, 254,
      112, 200, 160, 254, 121, 200, 155, 254, 130, 200, 150, 254, 139, 200, 145, 254, 148, 200, 140, 254,
      157, 200, 135, 254, 166, 200, 130, 254, 175, 200, 125, 254, 184, 200, 120, 254, 193, 200, 115, 254,
      202, 200, 110, 254, 211, 200, 105, 254, 220, 200, 100, 254, 229, 200, 95, 254, 238, 200, 90, 254,
      247, 200, 85, 254, 40, 210, 200, 254, 49, 210, 195, 254, 58, 210, 190, 254, 67, 210, 185, 254,
      76, 210, 180, 254, 85, 210, 175, 254, 94, 210, 170, 254, 103, 210, 165, 254, 112, 210, 160, 254,
      121, 210, 155, 254, 130, 210, 150, 254, 139, 210, 145, 254, 148, 210, 140, 254, 157, 210, 135, 254,
      166, 210, 130, 254, 175, 210, 125, 254, 184, 210, 120, 254, 193, 210, 115, 254, 202, 210, 110, 254,
      211, 210, 105, 254, 220, 210, 100, 254, 229, 210, 95, 254, 238, 210, 90, 254, 247, 210, 85, 0,
      0, 0, 0, 0, 0, 0, 1];
   DEMO_PPM : constant Byte_String := 
     [80, 54, 10, 35, 32, 100, 101, 109, 111, 10, 51, 32, 50, 10, 50, 53, 53, 10, 255, 0,
      0, 0, 255, 0, 0, 0, 255, 255, 255, 0, 0, 255, 255, 255, 255, 255];

   procedure Read_Binary (Name : String; Result : out Storage_Result) is
      procedure Serve (Data : Byte_String) is
         Keep_Going : Boolean := True;
         First : Positive := Data'First;
      begin
         while Keep_Going and then First <= Data'Last loop
            declare
               Last : constant Natural := Natural'Min (Data'Last, First + Maximum_Chunk - 1);
               Chunk : String (1 .. Last - First + 1);
            begin
               for I in Chunk'Range loop
                  Chunk (I) := Character'Val (Data (First + I - 1));
               end loop;
               Consume (Chunk, Keep_Going);
               First := Last + 1;
            end;
         end loop;
         Result := Succeeded;
      end Serve;
   begin
      Result := Invalid_Name;
      if not Valid_Image_Name (Name) then return; end if;
      if Name = "demo.qoi" then Serve (DEMO_QOI);
      elsif Name = "demo.ppm" then Serve (DEMO_PPM);
      else Result := Not_Found;
      end if;
   end Read_Binary;
end CCL_Workspace;
