with Ada.Text_IO;
with Interfaces; use Interfaces;
with Hardware_Authority;
with Hardware_Catalog;
with Hardware_Grants; use Hardware_Grants;
procedure Hardware_Grants_Tests is
   package C renames Hardware_Catalog;
   S, Before : State;
   Catalog : C.State;
   Root, Child, Leaf, Other, H : Handle;
   OK : Boolean;
   P : Hardware_Authority.Permission := (1, True, True, True, 255);
   D : C.Descriptor := (P, C.ACPI, C.Memory_Space, 4096, 1);
   Checks : Natural := 0;
   procedure Check (B : Boolean) is
   begin
      Checks := Checks + 1;
      if not B then raise Program_Error with Checks'Image; end if;
   end Check;
begin
   Admit_Group (S, Catalog, C.ACPI, Root); Check (Root = 0);
   Check (not Live (S, 0) and not Live (S, Unsigned_64'Last));
   Initialize (S, OK); Check (OK and Identity (S) /= 0);
   C.Begin_Inventory (Catalog, OK); Check (OK);
   C.Add (Catalog, D, OK); Check (OK);
   D.Group := C.GPIO; D.Permission.Resource_ID := 2;
   C.Add (Catalog, D, OK); Check (OK);
   C.Seal (Catalog, OK); Check (OK);
   Admit_Group (S, Catalog, C.ACPI, Root); Check (Live (S, Root));
   Admit_Group (S, Catalog, C.GPIO, Other); Check (Live (S, Other));
   Check (not Resolve (S, Catalog, Root, False, 0).Allowed);
   Before := S; Derive (S, Catalog, Other, P, H); Check (H = 0 and S = Before);
   P.Write_Mask := 15;
   Derive (S, Catalog, Root, P, Child); Check (Live (S, Child));
   Check (Resolve (S, Catalog, Child, True, 15).Allowed);
   Check (not Resolve (S, Catalog, Child, True, 16).Allowed);
   P.Write_Mask := 31;
   Before := S; Derive (S, Catalog, Child, P, H); Check (H = 0 and S = Before);
   P.Write_Mask := 3; P.Readable := False; P.Delegable := False;
   Derive (S, Catalog, Child, P, Leaf); Check (Live (S, Leaf));
   Check (Resolve (S, Catalog, Leaf, True, 3).Allowed);
   Check (not Resolve (S, Catalog, Leaf, False, 0).Allowed);
   Before := S; Derive (S, Catalog, Leaf, P, H); Check (H = 0 and S = Before);
   Revoke (S, Child);
   Check (not Live (S, Child) and not Live (S, Leaf));
   Check (Live (S, Root) and Live (S, Other));
   Check (not Resolve (S, Catalog, Leaf, True, 3).Allowed);
   Derive (S, Catalog, Root, P, H); Check (H > Leaf and Live (S, H));
   Revoke (S, Root); Check (not Live (S, H) and Live (S, Other));
   Before := S; Revoke (S, Unsigned_64'Last); Check (S = Before);
   P.Resource_ID := 2;
   Derive (S, Catalog, Other, P, Leaf); Check (Live (S, Leaf));
   C.Revoke (Catalog);
   Check (not Resolve (S, Catalog, Leaf, True, 1).Allowed);
   Before := S; Derive (S, Catalog, Other, P, H); Check (H = 0 and S = Before);
   C.Begin_Inventory (Catalog, OK); Check (OK);
   C.Add (Catalog, D, OK); Check (OK); C.Seal (Catalog, OK); Check (OK);
   Check (not Resolve (S, Catalog, Leaf, True, 1).Allowed);
   Admit_Group (S, Catalog, C.GPIO, Root); Check (Live (S, Root));
   Derive (S, Catalog, Root, P, Leaf); Check (Resolve (S, Catalog, Leaf, True, 1).Allowed);
   -- Long ancestor chains retain transitive revocation and never reuse IDs.
   P.Delegable := True;
   Derive (S, Catalog, Root, P, Child); Check (Live (S, Child));
   Other := Child;
   while Count (S) < Maximum_Grants loop
      Derive (S, Catalog, Other, P, H); Check (H > Other and Live (S, H));
      Other := H;
   end loop;
   Before := S; Derive (S, Catalog, Other, P, H); Check (H = 0 and S = Before);
   Revoke (S, Child); Check (not Live (S, Other) and Live (S, Leaf));
   Before := S; Admit_Group (S, Catalog, C.GPIO, H); Check (H = 0 and S = Before);
   declare
      G : State;
      Inventory, Saved : C.State;
      A, B : Handle;
      Ticket, Denied_Ticket : Unsigned_64;
      Result : C.Decision;
      Control : constant C.Descriptor :=
        ((7, True, True, True, 255), C.ACPI, C.Memory_Space, 8192, 1);
      Narrow : constant Hardware_Authority.Permission := (7, False, True, False, 3);
      use type C.State;
   begin
      Initialize (G, OK); Check (OK and Identity (G) /= Identity (S));
      C.Begin_Inventory (Inventory, OK); Check (OK);
      C.Add (Inventory, Control, OK); Check (OK);
      C.Seal (Inventory, OK); Check (OK);
      Admit_Group (G, Inventory, C.ACPI, A);
      Derive (G, Inventory, A, Narrow, B); Check (Live (G, B));
      Saved := Inventory;
      Begin_Access (G, Inventory, A, True, 1, Result, Ticket);
      Check (not Result.Allowed and Ticket = 0 and Inventory = Saved);
      Begin_Access (G, Inventory, Unsigned_64'Last, True, 1, Result, Ticket);
      Check (not Result.Allowed and Ticket = 0 and Inventory = Saved);
      Begin_Access (G, Inventory, B, False, 0, Result, Ticket);
      Check (not Result.Allowed and Ticket = 0 and Inventory = Saved);
      Begin_Access (G, Inventory, B, True, 4, Result, Ticket);
      Check (not Result.Allowed and Ticket = 0 and Inventory = Saved);
      Begin_Access (G, Inventory, B, True, 3, Result, Ticket);
      Check (Result.Allowed and Ticket /= 0 and C.Busy (Inventory));
      Check (Result.Resource.Address = 8192 and Result.Resource.Width = 1);
      Saved := Inventory;
      Begin_Access (G, Inventory, B, True, 1, Result, Denied_Ticket);
      Check (not Result.Allowed and Denied_Ticket = 0 and Inventory = Saved);
      Revoke (G, A);
      Check (not Live (G, B) and C.Busy (Inventory));
      Begin_Access (G, Inventory, B, True, 1, Result, Denied_Ticket);
      Check (not Result.Allowed and Inventory = Saved);
      Admit_Group (G, Inventory, C.ACPI, A); Check (Live (G, A));
      Derive (G, Inventory, A, Narrow, B); Check (Live (G, B));
      C.Revoke (Inventory); Check (not C.Ready_To_Release (Inventory));
      C.Begin_Inventory (Inventory, OK); Check (not OK);
      C.Finish_Access (Inventory, Ticket + 1, OK); Check (not OK and C.Busy (Inventory));
      C.Finish_Access (Inventory, Ticket, OK); Check (OK and C.Ready_To_Release (Inventory));
      C.Finish_Access (Inventory, Ticket, OK); Check (not OK);
      C.Begin_Inventory (Inventory, OK); Check (OK);
      C.Add (Inventory, Control, OK); Check (OK); C.Seal (Inventory, OK); Check (OK);
      Saved := Inventory;
      Begin_Access (G, Inventory, B, True, 1, Result, Denied_Ticket);
      Check (not Result.Allowed and Denied_Ticket = 0 and Inventory = Saved);
   end;
   Ada.Text_IO.Put_Line ("HARDWARE-GRANTS: PASS" & Checks'Image);
end Hardware_Grants_Tests;
