with Region_Registry;
with Interfaces; use Interfaces;
with Ada.Text_IO;
procedure Registry_Tests is
   package R is new Region_Registry (2, 16#10000#, 16#20000#);
   use type R.Phase;
   Object : R.Registry;
   A, B, C : R.Handle;
   OK : Boolean;
begin
   R.Reserve (Object, 0, 16#10000#, 4096, A, OK);
   pragma Assert (not OK);
   R.Reserve (Object, 1, Unsigned_64'Last - 4095, 8192, A, OK);
   pragma Assert (not OK);
   R.Reserve (Object, 1, 16#10000#, 8192, A, OK);
   pragma Assert (OK and R.State (Object, 1, A) = R.Reserved);
   pragma Assert (R.Describe (Object, 1, A).Base = 16#10000#);
   pragma Assert (R.Describe (Object, 1, A).Bytes = 8192);
   pragma Assert (R.Describe (Object, 2, A).Base = 0);
   pragma Assert (not R.Overlaps (Object, 1, 0, 16#10000#));
   pragma Assert (R.Overlaps (Object, 1, 0, 16#10001#));
   pragma Assert (R.Overlaps (Object, 1, 16#11FFF#, 1));
   pragma Assert (not R.Overlaps (Object, 1, 16#12000#, 1));
   pragma Assert (not R.Overlaps (Object, 1, 16#30000#, 4096));
   pragma Assert (R.Overlaps (Object, 1, Unsigned_64'Last - 1, 4));
   pragma Assert (R.Overlaps (Object, 1, 16#30000#, 0));
   pragma Assert (R.Overlaps (Object, 1, 16#11000#, 8192));
   pragma Assert (not R.Overlaps (Object, 1, 16#12000#, 4096));
   R.Commit (Object, 2, A, OK);
   pragma Assert (not OK);
   R.Commit (Object, 1, A, OK);
   pragma Assert (not OK);
   R.Bind_Backing (Object, 2, A, 16#40000#, OK);
   pragma Assert (not OK);
   R.Bind_Backing (Object, 1, A, 16#40001#, OK);
   pragma Assert (not OK);
   R.Bind_Backing (Object, 1, A, 16#40000#, OK);
   pragma Assert (OK and R.Physical_Overlap (Object, 16#41FFF#, 1));
   pragma Assert (not R.Physical_Overlap (Object, 16#42000#, 1));
   R.Bind_Backing (Object, 1, A, 16#50000#, OK);
   pragma Assert (not OK);
   R.Commit (Object, 1, A, OK);
   pragma Assert (OK);
   R.Finish_Retirement (Object, 1, A, OK);
   pragma Assert (not OK and R.State (Object, 1, A) = R.Live);
   R.Reserve (Object, 2, 16#10000#, 8192, B, OK);
   pragma Assert (OK);
   R.Bind_Backing (Object, 2, B, 16#41000#, OK);
   pragma Assert (not OK);
   R.Reserve (Object, 1, 16#12000#, 4096, C, OK);
   pragma Assert (not OK);
   R.Begin_Retirement (Object, 1, A, OK);
   pragma Assert (OK and R.Overlaps (Object, 1, 16#10000#, 4096));
   pragma Assert (R.Physical_Overlap (Object, 16#40000#, 8192));
   R.Commit (Object, 1, A, OK);
   pragma Assert (not OK);
   R.Finish_Retirement (Object, 1, A, OK);
   pragma Assert (OK and R.State (Object, 1, A) = R.Absent);
   pragma Assert (not R.Physical_Overlap (Object, 16#40000#, 8192));
   R.Bind_Backing (Object, 2, B, 16#40000#, OK);
   pragma Assert (OK);
   R.Reserve (Object, 1, 16#10000#, 8192, C, OK);
   pragma Assert (OK and C.Index = A.Index and C.Generation /= A.Generation);
   pragma Assert (R.Describe (Object, 1, A).Base = 0);
   R.Begin_Retirement (Object, 1, A, OK);
   pragma Assert (not OK and R.State (Object, 1, C) = R.Reserved);
   R.Begin_Retirement (Object, 2, B, OK);
   pragma Assert (OK);
   R.Finish_Retirement (Object, 2, B, OK);
   pragma Assert (OK);
   Ada.Text_IO.Put_Line ("PASS: region identities, overlap, capacity, retirement and stale handles");
end Registry_Tests;
