with Ada.Text_IO; use Ada.Text_IO;
with Interfaces; use Interfaces;
with Proof_Driver; use Proof_Driver;
with Deadline_Ownership;
procedure Main is
   use Deadlines;
   S, Other_CPU : State;
   A, B : Ticket;
   OK : Boolean;
   R : Outcome;
   Late : Tick;
   package Small is new Deadline_Ownership (Identity, (0, 0), 3);
   Tiny : Small.State;
   T : Small.Ticket;
   Before : Small.Snapshot;
   use type Small.Snapshot;
begin
   Arm (Other_CPU, (0, 0), 100, A, OK);
   pragma Assert (not OK and not View (Other_CPU).Active and View (Other_CPU).Serial = 0);
   for I in 1 .. 10_000 loop
      Arm (S, (5, 1), 100, A, OK);
      pragma Assert (OK);
      Arm (S, (5, 2), 200, B, OK);
      pragma Assert (OK and A /= B);
      Cancel (S, (5, 1), A, OK);
      pragma Assert (not OK and View (S).Active);
      Cancel (S, (5, 2), A, OK);
      pragma Assert (not OK and View (S).Active);
      Poll (S, 100, (5, 2), R, Late);
      pragma Assert (R = Nothing_Due and View (S).Active);
      pragma Assert (Next_Interrupt (S, 150) = 150 and Next_Interrupt (S, 300) = 200);
      Poll (S, 205, (5, 2), R, Late);
      pragma Assert (R = Expired and Late = 5);
      Poll (S, 210, (5, 2), R, Late);
      pragma Assert (R = Nothing_Due and Late = 0);
      pragma Assert (not View (Other_CPU).Active);
   end loop;
   Arm (S, (7, 10), 30, A, OK);
   Poll (S, 30, (7, 11), R, Late);
   pragma Assert (R = Stale_Owner and not View (S).Active);
   Arm (S, (7, 11), Tick'Last, A, OK);
   Poll (S, Tick'Last - 1, (7, 11), R, Late);
   pragma Assert (R = Nothing_Due);
   Poll (S, Tick'Last, (7, 11), R, Late);
   pragma Assert (R = Expired and Late = 0);
   Arm (S, (7, 11), 0, A, OK);
   Poll (S, Tick'Last, (7, 11), R, Late);
   pragma Assert (R = Expired and Late = Tick'Last);
   Arm (S, (7, 11), 90, A, OK);
   Cancel (S, (7, 11), A, OK);
   pragma Assert (OK and Next_Interrupt (S, 500) = 500);
   Poll (S, 100, (7, 11), R, Late);
   pragma Assert (R = Nothing_Due);
   for I in 1 .. 3 loop
      Small.Arm (Tiny, (1, 1), 100, T, OK);
      pragma Assert (OK and T = Unsigned_64 (I));
   end loop;
   Before := Small.View (Tiny);
   Small.Arm (Tiny, (1, 2), 200, T, OK);
   pragma Assert (not OK and T = 0 and Small.View (Tiny) = Before);
   Small.Arm (Tiny, (0, 0), 0, T, OK);
   pragma Assert (not OK and Small.View (Tiny) = Before);
   Put_Line ("DEADLINE-OWNER-CHECK: PASS replacement, stale IRQ/cancel, exactly-once expiry, CPU isolation, tick limits, ticket exhaustion");
end Main;
