with Test_Namespace; use Test_Namespace;

with AML_Objects.Byte_References; use AML_Objects.Byte_References;
with AML_Objects;
with AML_Objects.Package_References;
with AML_Decode; use AML_Decode;
with Ada.Text_IO;
with AML_Execute; use AML_Execute;
with Ada.Command_Line;
procedure Namespace_Owner_Tests is
 package Test_Owner renames Test_Namespace.Owned;
 use Test_Owner;
 use type Byte;
 use type Integer_Value;
 A, B : Arena;
 Element_Ref, Alias_Ref : Test_Owner.Reference;
 Element_ID, Package_ID : AML_Objects.Object_ID;
 Element_Status : AML_Objects.Package_References.Result_Status;
 use type AML_Objects.Package_References.Result_Status;
 R, Later, String_Ref : Test_Owner.Reference;
 OK : Boolean; Result : Load_Status; Status : Result_Status; V : Byte;
 Copy : State := Empty;
 Checks : Natural := 0;
 Write_Result : Execution_Status;
 Resolved : Datum;
 Package_Fixture : constant Bytes := [16#08#,16#50#,16#4B#,16#47#,16#30#,16#12#,6,2,16#0A#,1,16#0A#,2];
 String_Fixture : constant Bytes := [16#08#,16#53#,16#54#,16#52#,16#30#,16#0D#,97,98,0];
 Second_Fixture : Bytes (1 .. 11);
 -- Name(BUF0, Buffer(2){3,4})
 Fixture : constant Bytes := [16#08#,16#42#,16#55#,16#46#,16#30#,
   16#11#,16#05#,16#0A#,16#02#,16#03#,16#04#];
 procedure Check (C : Boolean) is
 begin if not C then raise Program_Error with Natural'Image (Checks); end if;
 Checks := Checks + 1; end Check;
begin
 if Ada.Command_Line.Argument_Count = 1 then
   Check (Ada.Command_Line.Argument (1) /= "--negative-control");
 end if;
 Read (A, R, V, OK); Check (not OK and V = 0);
 Write (A, R, 99, OK); Check (not OK);
 Reset (A, OK); Check (OK);
 Load (A, Fixture, Bits_64, Result); Check (Result = Loaded);
 Copy := Snapshot (A); Check (Count (Copy) = 1);
 Make (A, Data_Object (Copy, 1), 0, R, Status); Check (Status = Ready);
 Read (A, R, V, OK); Check (OK and V = 3);
 Write (A, R, 9, OK); Check (OK);
 Check (Buffer_Data (Copy, 1) (1) = 3);
 Check (Buffer_Data (Snapshot (A), 1) (1) = 9);
 Second_Fixture := Fixture; Second_Fixture (5) := 16#31#;
 Load (A, Second_Fixture, Bits_64, Result); Check (Result = Loaded);
 Check (Count (Snapshot (A)) = 2);
 Read (A, R, V, OK); Check (OK and V = 9);
 Make (A, Data_Object (Snapshot (A), 2), 1, Later, Status); Check (Status = Ready);
 Write (A, Later, 44, OK); Check (OK);
 Read (A, R, V, OK); Check (OK and V = 9);
 Check (Buffer_Data (Snapshot (A), 2) (2) = 44);
 Check (Count (Copy) = 1 and Buffer_Data (Copy, 1) (1) = 3);
 Load (A, String_Fixture, Bits_64, Result); Check (Result = Loaded);
 Make (A, Data_Object (Snapshot (A), 3), 1, String_Ref, Status); Check (Status = Ready);
 Read (A, String_Ref, V, OK); Check (OK and V = 98);
 Write (A, String_Ref, 99, OK); Check (OK);
 Check (String_Data (Snapshot (A), 3) = "ac");
 Read (A, R, V, OK); Check (OK and V = 9);
 Reset (B, OK); Check (OK);
 Load (B, Fixture, Bits_64, Result); Check (Result = Loaded);
 Read (B, R, V, OK); Check (not OK and V = 0);
 Write (B, R, 99, OK); Check (not OK);
 Check (Buffer_Data (Snapshot (B), 1) (1) = 3);
 Load (A, Fixture, Bits_64, Result); Check (Result /= Loaded);
 Read (A, R, V, OK); Check (OK and V = 9);
 Reset (A, OK); Check (OK);
 Load (A, Fixture, Bits_64, Result); Check (Result = Loaded);
 Read (A, String_Ref, V, OK); Check (not OK and V = 0);
 Read (A, R, V, OK); Check (not OK);
 Write (A, R, 99, OK); Check (not OK);
 Check (Buffer_Data (Snapshot (A), 1) (1) = 3);
 Load (A, Package_Fixture, Bits_64, Result); Check (Result = Loaded);
 Package_ID := Data_Object (Snapshot (A), 2);
 Make_Element (A, Package_ID, 0, Element_Ref, Element_Status);
 Check (Element_Status = AML_Objects.Package_References.Ready);
 Alias_Ref := Element_Ref;
 Read_Element (A, Element_Ref, Element_ID, OK); Check (OK and Element_ID /= 0);
 Write_Element (A, Element_Ref, 0, OK); Check (OK);
 Read_Element (A, Alias_Ref, Element_ID, OK); Check (OK and Element_ID = 0);
 Write_Element (A, Element_Ref, AML_Objects.Object_ID'Last, OK); Check (not OK);
 Read_Element (A, Alias_Ref, Element_ID, OK); Check (OK and Element_ID = 0);
 Read (A, Element_Ref, V, OK); Check (not OK and V = 0);
 Write (A, Element_Ref, 99, OK); Check (not OK);
 Make (A, Data_Object (Snapshot (A), 1), 0, R, Status); Check (Status = Ready);
 Read_Element (A, R, Element_ID, OK); Check (not OK and Element_ID = 0);
 Write_Element (A, R, 0, OK); Check (not OK);
 Read_Element (B, Element_Ref, Element_ID, OK); Check (not OK and Element_ID = 0);
 Write_Element (B, Element_Ref, 0, OK); Check (not OK);
 Reset (A, OK); Check (OK);
 Load (A, Package_Fixture, Bits_64, Result); Check (Result = Loaded);
 Read_Element (A, Element_Ref, Element_ID, OK); Check (not OK and Element_ID = 0);
 Write_Element (A, Alias_Ref, 0, OK); Check (not OK);
 Store_Integer (A, Alias_Ref, 42, Write_Result); Check (Write_Result = Unsupported_Value);
 Make_Element (A, Data_Object (Snapshot (A), 1), 0, Element_Ref, Element_Status);
 Check (Element_Status = AML_Objects.Package_References.Ready);
 Copy := Snapshot (B);
 Store_Integer (B, Element_Ref, 42, Write_Result); Check (Write_Result = Unsupported_Value);
 Check (Snapshot (B) = Copy);
 Store_Integer (A, Element_Ref, Integer_Value'Last, Write_Result); Check (Write_Result = Returned);
 Resolve_Value (A, Element_Ref, Resolved, Write_Result);
 Check (Write_Result = Returned and then Resolved.Value_Kind = Integer_Datum and then Resolved.Number = Integer_Value'Last);
 Load (A, Fixture, Bits_64, Result); Check (Result = Loaded);
 Make (A, Data_Object (Snapshot (A), 2), 0, R, Status); Check (Status = Ready);
 Store_Integer (A, R, 16#1234#, Write_Result); Check (Write_Result = Returned);
 Read (A, R, V, OK); Check (OK and V = 16#34#);
 Ada.Text_IO.Put_Line ("Owned namespace explicit checks:" & Natural'Image (Checks) & " PASS");
end Namespace_Owner_Tests;
