#!/usr/bin/env python3
"""Generate validated SPIR-V for the Vulkan compositor affine renderer (Nix host tools)."""
from pathlib import Path
import hashlib
import json
import struct
import subprocess
import sys

root = Path(__file__).resolve().parents[2] / "userspace/lib/compositor"
out = Path(sys.argv[1]).resolve()
out.mkdir(parents=True, exist_ok=True)
header = ["/* Generated by build-vulkan-affine-shaders.py; not GPU machine code. */",
          "#include <stdint.h>"]
hashes = {}
defines = ["-DCUBIT_VULKAN_TEST_FORCE_DIVIDE=1"] if "--force-divide" in sys.argv[2:] else []
hashes["test_defines"] = defines
for suffix, name in (("vert", "vertex"), ("frag", "fragment")):
    source = root / ("vulkan_affine." + suffix)
    binary = out / ("vulkan_affine." + suffix + ".spv")
    subprocess.run(["glslangValidator", "-V", "--target-env", "vulkan1.0",
                    *defines, str(source), "-o", str(binary)], check=True)
    subprocess.run(["spirv-val", "--target-env", "vulkan1.0", str(binary)], check=True)
    data = binary.read_bytes()
    if len(data) % 4 or data[:4] != b"\x03\x02\x23\x07":
        raise SystemExit("invalid SPIR-V output")
    words = struct.unpack("<" + "I" * (len(data) // 4), data)
    header.append(f"static const uint32_t vulkan_affine_{name}[] = {{")
    header.extend("  " + ", ".join(f"0x{x:08x}" for x in words[i:i+8]) + ","
                  for i in range(0, len(words), 8))
    header.append("};")
    hashes[source.name] = hashlib.sha256(source.read_bytes()).hexdigest()
    hashes[binary.name] = hashlib.sha256(data).hexdigest()
(out / "vulkan-affine-shaders.h").write_text("\n".join(header) + "\n")
checker = ["/* Generated descriptor-free checker shaders. */", "#include <stdint.h>"]
for source_name, role in (("vulkan_affine.vert", "vertex"), ("vulkan_checker.frag", "fragment")):
    source = root / source_name
    binary = out / (source_name + ".spv")
    if role == "fragment":
        subprocess.run(["glslangValidator", "-V", "--target-env", "vulkan1.0", str(source), "-o", str(binary)], check=True)
        subprocess.run(["spirv-val", "--target-env", "vulkan1.0", str(binary)], check=True)
    data = binary.read_bytes()
    if len(data) % 4 or data[:4] != b"\x03\x02\x23\x07":
        raise SystemExit("invalid checker SPIR-V")
    words = struct.unpack("<" + "I" * (len(data) // 4), data)
    checker.append(f"static const uint32_t vulkan_checker_{role}[] = {{")
    checker.extend("  " + ", ".join(f"0x{x:08x}" for x in words[i:i+8]) + "," for i in range(0, len(words), 8))
    checker.append("};")
    hashes[source.name] = hashlib.sha256(source.read_bytes()).hexdigest()
    hashes[binary.name] = hashlib.sha256(data).hexdigest()
(out / "vulkan-checker-shaders.h").write_text("\n".join(checker) + "\n")
(out / "shader-hashes.json").write_text(json.dumps(hashes, indent=2) + "\n")
print("Validated Vulkan1.0 shaders:", out)
