#ifndef CUBIT_NATIVE_SCENE_BRIDGE_H
#define CUBIT_NATIVE_SCENE_BRIDGE_H
#include <stdint.h>
/* Trusted same-device CuBit integration fixture, NOT a public GPU-import ABI.
 * One externally serialized session per linked image; run Ada elaboration once
 * before any call. All result/slot pointers must be valid writable uint32_t.
 *
 * Results: 0 success, 1 pending/deferred, 2 rejected, 3 uncertain/quarantined.
 * A rejected operation leaves existing ownership in effect. Code 3 is sticky:
 * retain device, command/fence, source, targets and all referenced resources.
 * No timeout is completion, and there is no force-reset or abandon/free API.
 *
 * Open takes private cubit_vulkan_target_request, three fresh private
 * cubit_vulkan_owned_image requests, initialized cubit_vulkan_submission and
 * immutable cubit_vulkan_affine_draw. All must name the SAME VkDevice;
 * the draw must name the submission command and an engine compatible with
 * the target pass. Width/height 12..65535, matching every request/draw.
 * Three targets: BGRA8_UNORM, COLOR_ATTACHMENT | TRANSFER_SRC. Actual image
 * requirements are charged before allocation against a 16 MiB session budget.
 * Source: BGRA8_UNORM, SAMPLED usage, same dimensions, nonaliasing, fully ready
 * before compositor sampling. Descriptor uses SHADER_READ_ONLY_OPTIMAL and
 * the affine engine's sampler/layout. No layout transitions occur in Open.
 * Source backing/view/descriptor/engine/context stay immutable and retained
 * from successful Open until successful Close, including between frames.
 * Code 2 from an initial Open is clean rejection (no retained backing); code 2
 * from a repeated Open does NOT release the prior live session.
 *
 * Normal flow:
 *  open; begin -> slot; [caller preparation barriers]; record;
 *  [caller color->transfer barrier, selected-target readback, transfer->host];
 *  submit; poll until 0; [CPU consume/present readback]; release; ...; close.
 * Begin starts the command buffer; Record ends its render pass but not the
 * command buffer. Submit seals and queues once. Poll never waits or resets.
 * Readback must be part of this SAME submission, so Poll=0 covers its writes.
 * Host noncoherent memory still requires invalidation before CPU access.
 * Target pass must preserve/initialize its attachment consistently with its
 * declared initial layout and the caller's pre-pass barriers.
 *
 * Release is caller evidence that every CPU consumer has finished. Do not
 * call it merely because a presentation request was accepted. While ready is
 * held, Begin and Close reject. There is no physical display/scanout authority
 * in this fixture. On timeout keep polling, retaining ALL referenced objects;
 * Cancel only accepts never-submitted recording, never Pending. Close frees
 * views before backing and releases the borrowed source only on result 0.
 * A fully closed session can Open fresh requests for another cycle.
 */
/* Generated by the CuBit Ada binder. Call exactly once per process. */
void compositor_sceneinit(void);
void cubit_native_scene_open(void *description,void *a,void *b,void *c,
    void *submission,void *source,uint32_t allowed,uint32_t width,uint32_t height,
    uint32_t *result);
void cubit_native_scene_begin(uint32_t *slot,uint32_t *result);
void cubit_native_scene_record(uint32_t *result);
void cubit_native_scene_submit(uint32_t *result);
void cubit_native_scene_poll(uint32_t *result);
void cubit_native_scene_cancel(uint32_t *result);
void cubit_native_scene_release(uint32_t *result);
void cubit_native_scene_close(uint32_t *result);
#endif
