from pathlib import Path
import tempfile,subprocess,os,json,hashlib
assert os.environ.get('IN_NIX_SHELL')
r=Path(__file__).resolve().parents[2];w=Path(tempfile.mkdtemp(prefix='software-facade-',dir=r/'tests/compositor/build'));print(w,flush=True)
names=['compositor_software_text','compositor_software_text_target','desktop_composition','compositor_text','compositor_glyph_cache','compositor_glyph_storage','compositor_glyph_software','compositor_glyph_placement','compositor_glyph_layout','compositor_glyph_memory','compositor_glyph_arena','compositor_glyph_ffi','compositor_identity','compositor_affine','compositor_transform','compositor_formats','heap_extents','cubit-display_geometry','cubit']
inputs={}
for name in names:
 for ext in ['ads','adb']:
  hits=[p for folder in ['userspace/lib/compositor','userspace/lib/display','userspace/runtime/gnat','userspace/allocator/src'] if (p:=r/folder/(name+'.'+ext)).exists()]
  if not hits:continue
  p=hits[0];data=p.read_bytes();(w/p.name).write_bytes(data);inputs[str(p.relative_to(r))]=hashlib.sha256(data).hexdigest()
for path in ['userspace/lib/compositor/desktop_compositor.ads','userspace/services/desktop/backend-legacy/desktop_compositor.adb']:
 p=r/path;data=p.read_bytes();(w/p.name).write_bytes(data);inputs[path]=hashlib.sha256(data).hexdigest()
(w/'raster.c').write_text('#include <stdint.h>\n#include <string.h>\n#include <assert.h>\nstatic unsigned fail;\nvoid fail_code(unsigned code){fail=code;}\nstruct request {uint32_t font,code,n,d,w,h,pitch,capacity;};\nstruct metrics {uint32_t advance,height;};\nuint32_t cubit_font_raster_mask(const struct request *r,void *pixels,struct metrics *m){\n if(fail==r->code)return 1; assert(r->capacity>=r->pitch*r->h);\n for(unsigned y=0;y<r->h;y++)memset((uint8_t*)pixels+y*r->pitch,127,r->w);\n *m=(struct metrics){r->w,r->h};return 0;}\n')
(w/'software_facade_tests.adb').write_text('with Ada.Text_IO;\nwith Ada.Command_Line;\nwith Interfaces; use Interfaces;\nwith Desktop_Compositor;\nwith Compositor_Text;\nwith Compositor_Formats;\nprocedure Software_Facade_Tests is\n package D renames Desktop_Compositor;\n package T renames Compositor_Text;\n package F renames Compositor_Formats;\n use type D.Output_Start, D.Render_Completion, T.Scene_Decision;\n procedure Fault (Code : Unsigned_32) with Import, Convention => C, External_Name => "fail_code";\n type Pixels is array (Natural range <>) of Unsigned_32;\n Target : aliased Pixels (0 .. 80 * 72 - 1) := (others => 16#FF123456#);\n Before : Pixels (Target\'Range);\n Image : F.Image := (Target\'Address, 80, 72, 320, 1);\n Screen : T.G.Output := (80, 72, T.G.Unrotated, (5, 4), 0, 0);\n Items : T.Glyphs := (1 => (65, (0, 0, 8, 17)), 2 => (66, (8, 0, 16, 17)), others => <>);\n Drawn, Repaint, Restart : Boolean;\n Start : D.Output_Start;\n Completion : D.Render_Completion;\n procedure Draw (Length : T.Count := 2; Capacity : F.Byte_Count := 80 * 72 * 4) is\n begin\n D.Draw_Text (Image, Capacity, Screen, Items, Length, (0, 0, 80, 72), 16#FFFFFFFF#, False,\n              Drawn, Repaint, Restart);\n end Draw;\nbegin\n pragma Assert (D.Selected and D.Software_Text);\n D.Begin_Output (Target\'Address, Screen, False, Start); pragma Assert (Start = D.Started);\n Before := Target; Image.Writable := 0; Draw;\n pragma Assert (not Drawn and not Repaint and not Restart and Target = Before);\n Image.Writable := 1; Draw (Capacity => 1);\n pragma Assert (not Drawn and not Repaint and not Restart and Target = Before);\n Image.Width := 79; Draw;\n pragma Assert (not Drawn and not Repaint and not Restart and Target = Before);\n Image.Width := 80; Draw (Length => 0);\n pragma Assert (Drawn and not Repaint and not Restart and Target = Before);\n Before := Target;\n if Ada.Command_Line.Argument_Count > 0 then\n Fault (65); Draw;\n pragma Assert (not Drawn and not Repaint and not Restart and Target = Before);\n Fault (0); Draw;\n pragma Assert (not Drawn and not Repaint and not Restart and Target = Before);\n Ada.Text_IO.Put_Line ("PASS first glyph fault disables retained text safely");\n return;\n end if;\n Fault (66); Draw;\n pragma Assert (not Drawn and Repaint and not Restart and Target /= Before);\n pragma Assert (T.Finish (1, Repaint) = T.Replay);\n -- Publication must await replay; the facade reports the partial write.\n D.Complete_Output (Target\'Address, False, False, Completion);\n pragma Assert (Completion = D.Complete);\n Target := Before; Fault (0); Draw;\n pragma Assert (not Drawn and not Repaint and not Restart and Target = Before);\n D.Complete_Output (Target\'Address, False, True, Completion);\n pragma Assert (Completion = D.Complete);\n Ada.Text_IO.Put_Line ("PASS software facade: first/later glyph faults, replay recovery, readonly/short/mismatched targets, empty batch, quiescence");\nend Software_Facade_Tests;\n')
(w/'test.gpr').write_text('project Test is\nfor Source_Dirs use ("."); for Languages use ("Ada", "C");\nfor Object_Dir use "obj"; for Exec_Dir use "."; for Main use ("software_facade_tests.adb");\npackage Compiler is for Default_Switches ("Ada") use ("-gnat2022", "-gnata", "-gnato", "-O2"); end Compiler;\nend Test;')
for cmd in [['gprbuild','-q','-p','-P',str(w/'test.gpr')],['gnatprove','-P',str(w/'test.gpr'),'-u','desktop_compositor.adb','--level=2','--timeout=30','-j2']]:
 subprocess.run(['alr','exec','--',*cmd],cwd=r/'kernel',check=True)
subprocess.run([str(w/'software_facade_tests')],check=True)
subprocess.run([str(w/'software_facade_tests'),'first-fault'],check=True)
report=(w/'obj/gnatprove/gnatprove.out').read_text()
total=next(line for line in report.splitlines() if line.startswith('Total '))
assert total.split()[-2:]==['.','.'],total
for path,digest in inputs.items():assert hashlib.sha256((r/path).read_bytes()).hexdigest()==digest,path
(w/'result.json').write_text(json.dumps({'status':'PASS','proof':total,'inputs':inputs},indent=2))
print(total,flush=True)
