#!/usr/bin/env python3
"""Run inside nix develop. Export SVG icons and native straight-alpha pixels."""
from pathlib import Path
import subprocess
from PIL import Image
folder = Path(__file__).resolve().parent
root = folder.parents[1]
for size in (16, 24, 32, 64, 256):
    subprocess.run(['rsvg-convert', '-w', str(size), '-h', str(size),
                    '-o', str(folder / f'penny-{size}.png'), str(folder / 'penny.svg')], check=True)
lines = ['-- Generated by assets/penny/render.py; edit penny.svg instead.',
         'with CuBit.UI;', 'package Penny_Artwork is']
for size in (16, 32):
    pixels = Image.open(folder / f'penny-{size}.png').convert('RGBA')
    lines.append(f'   Globe_{size} : constant CuBit.UI.ARGB_Bitmap (0 .. {size-1}, 0 .. {size-1}) := [')
    for y in range(size):
        row = []
        for x in range(size):
            r, g, b, a = pixels.getpixel((x, y))
            row.append(f'16#{a:02X}{r:02X}{g:02X}{b:02X}#')
        lines.append('      [' + ', '.join(row) + ('],' if y < size-1 else ']];'))
lines.append('end Penny_Artwork;')
(root / 'userspace/servo/native/penny_artwork.ads').write_text('\n'.join(lines) + '\n')
