#!/usr/bin/env python3
"""Emit an Ada package holding DER bytes: der_to_ada.py PACKAGE NAME IN.der OUT.ads"""
import sys

package, name, source, target = sys.argv[1:5]
data = open(source, "rb").read()
lines = []
for start in range(0, len(data), 12):
    lines.append("      " + ", ".join(f"16#{b:02X}#" for b in data[start:start + 12]))
body = ",\n".join(lines)
text = f"""--  Generated by tools/der_to_ada.py from {source.split('/')[-1]}; do not edit.
pragma Ada_2022;
with X509;
package {package} is
   {name} : constant X509.Byte_Seq (0 .. {len(data) - 1}) :=
     [
{body}];
end {package};
"""
with open(target + ".tmp", "w") as out:
    out.write(text)
import os
if not os.path.exists(target) or open(target).read() != text:
    os.replace(target + ".tmp", target)
else:
    os.remove(target + ".tmp")
