#!/usr/bin/env python3
"""Rasterize the vendored Bluecurve toolbar SVGs into a compile-time Ada atlas.

Run inside nix develop (Pillow and rsvg-convert). No SVG/PNG decoder or
external theme files are required on CuBit. Output goes to stdout.
"""

import io
from pathlib import Path
import subprocess
import sys

from PIL import Image


ICONS = (
    ("Open_Document", "stock-open"),
    ("Save_Document", "stock-save"),
    ("Interpret_Source", "stock-execute"),
    ("Compile_Program", "icon-development"),
    ("Run_Program", "stock-media-play"),
    ("Pause_Program", "stock-media-pause"),
    ("Stop_Program", "stock-media-stop"),
    ("Step_Into", "stock-go-down"),
    ("Step_Over", "stock-redo"),
)
SOURCE = Path(__file__).resolve().parent.parent / "userspace/lib/ui/assets/bluecurve"
SIZE = 16


def generate():
    lines = [
        "--  Generated by tools/generate_toolbar_atlas.py; do not edit.",
        "--  Bluecurve @ 013ba225e78d9767b274ac6f16a67cb19f0673c6.",
        "--  See ASSET_LICENSES.md and assets/bluecurve for source artwork.",
        "private package CuBit.UI.Widgets.Bluecurve is",
        f"   Icon_Size : constant := {SIZE};",
        "   type Icon_Table is array (Toolbar_Icon) of",
        "     CuBit.UI.ARGB_Bitmap (0 .. Icon_Size - 1, 0 .. Icon_Size - 1);",
        "   Pixels : constant Icon_Table := [",
    ]
    for index, (name, source) in enumerate(ICONS):
        data = subprocess.check_output(["rsvg-convert", str(SOURCE / (source + ".svg"))])
        bitmap = Image.open(io.BytesIO(data)).convert("RGBA")
        if bitmap.size != (SIZE, SIZE):
            raise ValueError(f"{source}: expected {SIZE}x{SIZE}, got {bitmap.size}")
        lines.append(f"      --  {source}.svg; straight (not premultiplied) ARGB.")
        lines.append(f"      {name} => [")
        for y in range(SIZE):
            row = []
            for x in range(SIZE):
                r, g, b, a = bitmap.getpixel((x, y))
                row.append(f"16#{a:02X}{r:02X}_{g:02X}{b:02X}#")
            suffix = "," if y + 1 < SIZE else ""
            lines.append("         [" + ", ".join(row[:8]) + ",")
            lines.append("          " + ", ".join(row[8:]) + "]" + suffix)
        lines.append("      ]" + ("," if index + 1 < len(ICONS) else ""))
    lines += ["   ];", "end CuBit.UI.Widgets.Bluecurve;", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    sys.stdout.write(generate())
