#!/usr/bin/env python3
"""Build the desktop's application icon atlas (Desktop_Icons) from the
CuBit desktop icons (assets/desktop-icons, made by its make.py) and Penny's
own artwork (assets/penny). 24-pixel straight-alpha ARGB, one entry per
Desktop_Icons.Icon_ID literal, in this order.

Run from the repository root inside nix develop, after make.py:
  python3 tools/generate_desktop_icons.py
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "userspace/services/desktop/desktop_icons.ads"
SIZE = 24

# (Ada literal, PNG at SIZE, what it shows). Start is the OS logo on the
# Apps button; Category_* head the Apps menu's category rows.
ICONS = (
    ("Start", "assets/desktop-icons/png/cubit-24.png", "CuBit logo: purple cube, one teal face"),
    ("Workbench", "assets/desktop-icons/png/workbench-24.png", "CCL Workbench"),
    ("Console", "assets/desktop-icons/png/console-24.png", "CCL Console"),
    ("Logs", "assets/desktop-icons/png/logs-24.png", "Logs"),
    ("Trace", "assets/desktop-icons/png/trace-24.png", "Desktop trace"),
    ("Doom", "assets/desktop-icons/png/doom-24.png", "DOOM"),
    ("Devices", "assets/desktop-icons/png/devices-24.png", "Devices"),
    ("Penny", "assets/penny/penny-24.png", "Penny (her own artwork)"),
    ("Files", "assets/desktop-icons/png/files-24.png", "Files"),
    ("Gameboy", "assets/desktop-icons/png/gameboy-24.png", "SameBoy"),
    ("Settings", "assets/desktop-icons/png/settings-24.png", "Settings"),
    ("Inspector", "assets/desktop-icons/png/inspector-24.png", "Config Inspector"),
    ("Mesa", "assets/desktop-icons/png/mesa-24.png", "Mesa demos"),
    ("Boot", "assets/desktop-icons/png/boot-24.png", "Boot Diagnostics"),
    ("Power", "assets/desktop-icons/png/power-24.png", "Power"),
    ("Category_System", "assets/desktop-icons/png/system-24.png", "System category"),
    ("Category_Development", "assets/desktop-icons/png/development-24.png", "Development category"),
    ("Category_Web", "assets/desktop-icons/png/web-24.png", "Web category"),
    ("Category_Games", "assets/desktop-icons/png/games-24.png", "Games category"),
    ("Category_Media", "assets/desktop-icons/png/media-24.png", "Media category"),
    ("Category_Tools", "assets/desktop-icons/png/tools-24.png", "Tools category"),
)


def words(path):
    image = Image.open(ROOT / path).convert("RGBA")
    if image.size != (SIZE, SIZE):
        raise ValueError(f"{path}: expected {SIZE}x{SIZE}, got {image.size}")
    return [f"16#{a:02X}{r:02X}{g:02X}{b:02X}#" for r, g, b, a in image.getdata()]


def generate():
    lines = [
        "------------------------------------------------------------------------------",
        "--  CuBit",
        "--  Generated by tools/generate_desktop_icons.py; do not edit by hand.",
        "--  Sources: assets/desktop-icons (CuBit originals, make.py) and",
        "--  assets/penny (Penny's own artwork).",
        "------------------------------------------------------------------------------",
        "with Interfaces;",
        "",
        "package Desktop_Icons is",
        f"   ICON_SIZE : constant := {SIZE};",
        "   type Icon_ID is (",
    ]
    for index, (literal, _, shows) in enumerate(ICONS):
        lines.append(f"      {literal}{',' if index + 1 < len(ICONS) else ''}  --  {shows}")
    lines += [
        "   );",
        "   type Pixel_Array is array (Natural range <>) of Interfaces.Unsigned_32;",
        "   type Icon_Table is array (Icon_ID) of Pixel_Array (0 .. ICON_SIZE * ICON_SIZE - 1);",
        "",
        "   Pixels : constant Icon_Table := (",
    ]
    for index, (literal, path, _) in enumerate(ICONS):
        values = words(path)
        lines.append(f"      {literal} => (")
        rows = [", ".join(values[k:k + 8]) for k in range(0, len(values), 8)]
        lines.append(",\n".join("         " + row for row in rows))
        lines.append("      )" + ("," if index + 1 < len(ICONS) else ""))
    lines += ["   );", "end Desktop_Icons;", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    TARGET.write_text(generate())
    print(f"{len(ICONS)} icons -> {TARGET.relative_to(ROOT)}")
