with Ada.Text_IO; use Ada.Text_IO;
with Interfaces; use Interfaces;
with CuBit.Authority_Policy;
with CuBit.Protocols; use CuBit.Protocols;
with CuBit.Protocols.Stream_Connections; use CuBit.Protocols.Stream_Connections;
with CuBit.Protocols.Stream_Bindings; use CuBit.Protocols.Stream_Bindings;
procedure Lifecycle is
   Item : Binding (Identity => 7);
   Desired : Request;
   Evidence, Denied : Approvals;
   Token, Other : Unsigned_64;
   Outcome : Result;
   Before : View;
   function Approve (R : Request) return Approvals is
     ([others => (For_Connection => Key (R),
                  Outcome => CuBit.Authority_Policy.Approved)]);
begin
   Desired.Controller_Instance := 30;
   Desired.Binding := Reference (Item);
   Desired.Source.Reference := (10, 1, 1);
   Desired.Source.Direction := Output;
   Desired.Source.Profile.Element := INTEGER_64_CONTRACT;
   Desired.Source.Profile.Capacity.Payload_Bytes := 8;
   Desired.Destination := Desired.Source;
   Desired.Destination.Reference := (20, 1, 1);
   Desired.Destination.Direction := Input;
   Evidence := Approve (Desired);
   Before := Inspect (Item);
   Prepare (Item, Desired, Denied, Other, Outcome);
   pragma Assert (Outcome = Not_Authorized and Other = 0);
   pragma Assert (Inspect (Item) = Before);
   Prepare (Item, Desired, Evidence, Token, Outcome);
   pragma Assert (Outcome = Succeeded and Token /= 0);
   pragma Assert (not Inspect (Item).Active.Present);
   Before := Inspect (Item);
   Prepare (Item, Desired, Evidence, Other, Outcome);
   pragma Assert (Outcome = Busy and Inspect (Item) = Before);
   Commit (Item, 31, Token, Evidence, True, Outcome);
   pragma Assert (Outcome = Not_Authorized and Inspect (Item) = Before);
   Commit (Item, 30, Token + 1, Evidence, True, Outcome);
   pragma Assert (Outcome = Not_Authorized and Inspect (Item) = Before);
   Commit (Item, 30, Token, Evidence, False, Outcome);
   pragma Assert (Outcome = Resources_Not_Ready and Inspect (Item) = Before);
   Denied := Evidence;
   Denied (Release_To_Recipient).Outcome :=
     CuBit.Authority_Policy.Session_Denied;
   Commit (Item, 30, Token, Denied, True, Outcome);
   pragma Assert (Outcome = Not_Authorized and Inspect (Item) = Before);
   Commit (Item, 30, Token, Evidence, True, Outcome);
   pragma Assert (Outcome = Succeeded and Inspect (Item).Generation = 2);
   pragma Assert (Inspect (Item).State = Idle);
   pragma Assert (Inspect (Item).Active.Value = Desired);
   pragma Assert (Inspect (Item).Active.Transport_Ticket = Token);
   Before := Inspect (Item);
   Prepare (Item, Desired, Evidence, Other, Outcome);
   pragma Assert (Outcome = Stale_Binding and Inspect (Item) = Before);

   Desired.Binding := Reference (Item);
   Desired.Destination.Reference.Process_Instance := 21;
   Evidence := Approve (Desired);
   Prepare (Item, Desired, Evidence, Token, Outcome);
   pragma Assert (Outcome = Succeeded);
   pragma Assert (Inspect (Item).Active = Before.Active);
   Before := Inspect (Item);
   Abort_Preparation (Item, 31, Token, Outcome);
   pragma Assert (Outcome = Not_Authorized and Inspect (Item) = Before);
   Abort_Preparation (Item, 30, Token, Outcome);
   pragma Assert (Outcome = Succeeded and Inspect (Item).State = Retiring);
   pragma Assert (Inspect (Item).Active = Before.Active);
   Before := Inspect (Item);
   Finish_Retirement (Item, Token, False, Outcome);
   pragma Assert (Outcome = Resources_Not_Ready and Inspect (Item) = Before);
   Finish_Retirement (Item, Token + 1, True, Outcome);
   pragma Assert (Outcome = Not_Authorized and Inspect (Item) = Before);
   Finish_Retirement (Item, Token, True, Outcome);
   pragma Assert (Outcome = Succeeded and Inspect (Item).State = Idle);

   Prepare (Item, Desired, Evidence, Other, Outcome);
   pragma Assert (Outcome = Succeeded and Other /= Token);
   Commit (Item, 30, Token, Evidence, True, Outcome);
   pragma Assert (Outcome = Not_Authorized);
   Commit (Item, 30, Other, Evidence, True, Outcome);
   pragma Assert (Outcome = Succeeded and Inspect (Item).Generation = 3);
   pragma Assert (Inspect (Item).State = Retiring);
   pragma Assert (Inspect (Item).Active.Value = Desired);
   pragma Assert
     (Inspect (Item).Staged.Value.Destination.Reference.Process_Instance = 20);
   pragma Assert (Inspect (Item).Active.Transport_Ticket = Other);
   pragma Assert (Inspect (Item).Staged.Transport_Ticket = 1);
   Before := Inspect (Item);
   Desired.Binding := Reference (Item);
   Evidence := Approve (Desired);
   Prepare (Item, Desired, Evidence, Token, Outcome);
   pragma Assert (Outcome = Busy and Inspect (Item) = Before);
   Finish_Retirement (Item, Other, True, Outcome);
   pragma Assert (Outcome = Succeeded and Inspect (Item).State = Idle);
   Before := Inspect (Item);
   Finish_Retirement (Item, Other, True, Outcome);
   pragma Assert (Outcome = Wrong_Transition and Inspect (Item) = Before);
   Put_Line ("PASS: binding prepare/commit/abort/retire and stale-ticket lifecycle");
end Lifecycle;
