with Ada.Text_IO;
with System.Storage_Elements; use System.Storage_Elements;
with Interfaces; use Interfaces;
with Intel_GPU_VM_Image;
with Intel_GPU_VM_Image.Snapshots;
with Intel_GPU_ADLN_PPGTT; use Intel_GPU_ADLN_PPGTT;
procedure Descriptor_Storage_Tests is
   package VM is new Intel_GPU_VM_Image (8, Bootstrap_Descriptors => 4);
   package Snapshots is new VM.Snapshots;
   Source, Candidate : VM.Image;
   type Storage is array (1 .. 8192) of Unsigned_8;
   Source_Metadata, Candidate_Metadata : Storage := [others => 16#A5#] with Alignment => 4096;
   OK : Boolean;
   First : Natural;
   Epoch : Unsigned_64;
begin
   pragma Assert (VM.Backed_Tables (Source) = 0);
   pragma Assert (VM.Descriptor_Capacity (Source) = 4);
   VM.Initialize (Source, [4096, 8192, 12288, 16384, 20480, others => 0], OK, Backing_Count => 5);
   pragma Assert (not OK and VM.Backed_Tables (Source) = 0);
   VM.Initialize (Source, [4096, 8192, 12288, 16384, others => 0], OK, Backing_Count => 4);
   pragma Assert (OK and VM.Backed_Tables (Source) = 4 and VM.Used (Source) = 1);
   VM.Map_Page (Source, 4096, 16#100000#, Write_Back, Read_Write, OK);
   pragma Assert (OK and VM.Used (Source) = 4 and VM.Backed_Tables (Source) = 4);
   VM.Append_Offline_Backing (Source, [5 => 20480], First, OK);
   pragma Assert (not OK and VM.Backed_Tables (Source) = 4);
   Epoch := VM.Revision (Source);
   VM.Extend_Descriptors (Source, Unsigned_64 (To_Integer (Source_Metadata'Address)), 4096, OK);
   pragma Assert (OK and VM.Descriptor_Capacity (Source) = 8 and VM.Revision (Source) = Epoch);
   pragma Assert (VM.Lookup (Source, 4096) = Encode_Leaf (16#100000#, Write_Back, Read_Write));
   VM.Append_Offline_Backing (Source, [5 => 20480], First, OK);
   pragma Assert (OK and First = 5 and VM.Backed_Tables (Source) = 5);
   VM.Append_Offline_Backing (Source, [20480], First, OK);
   pragma Assert (not OK and First = 0 and VM.Backed_Tables (Source) = 5);
   pragma Assert (not VM.DMA_Disjoint (Source, 20480, 4096));
   pragma Assert (VM.DMA_Disjoint (Source, 24576, 4096));
   VM.Seal (Source, OK); pragma Assert (OK);
   VM.Prepare_Update (Candidate, Source,
     [40960, 45056, 49152, 53248, 57344, 61440, 0, 0], OK, Backing_Count => 6);
   pragma Assert (not OK and VM.Backed_Tables (Candidate) = 0);
   VM.Extend_Descriptors (Candidate, Unsigned_64 (To_Integer (Candidate_Metadata'Address)), 4096, OK);
   pragma Assert (OK);
   VM.Prepare_Update (Candidate, Source,
     [40960, 45056, 49152, 53248, 57344, 61440, 0, 0], OK, Backing_Count => 6);
   pragma Assert (OK and VM.Backed_Tables (Candidate) = 6 and VM.Used (Candidate) = 4);
   VM.Seal (Candidate, OK); pragma Assert (OK);
   Snapshots.Adopt_Committed (Source, Candidate, OK);
   pragma Assert (OK and VM.Backed_Tables (Source) = 6 and VM.Used (Source) = 4);
   pragma Assert (not VM.DMA_Disjoint (Source, 61440, 4096));
   Epoch := VM.Revision (Source);
   Snapshots.Forget_Retired (Source, Epoch, VM.Root_DMA (Source), False, OK);
   pragma Assert (not OK and VM.Backed_Tables (Source) = 6);
   Snapshots.Forget_Retired (Source, Epoch, VM.Root_DMA (Source), True, OK);
   pragma Assert (OK and VM.Backed_Tables (Source) = 0);
   VM.Initialize (Source, [81920, others => 0], OK, Backing_Count => 1);
   pragma Assert (OK and VM.Backed_Tables (Source) = 1 and VM.Used (Source) = 1);
   pragma Assert (for all I in 4097 .. 8192 => Source_Metadata (I) = 16#A5# and Candidate_Metadata (I) = 16#A5#);
   Ada.Text_IO.Put_Line ("Growable descriptors PASS: reserved/used distinction, rejected alias, snapshot adoption, authenticated retirement and reuse");
end Descriptor_Storage_Tests;
