with Ada.Text_IO;
with Interfaces; use Interfaces;
with Intel_GPU_PHY_Registers; use Intel_GPU_PHY_Registers;
procedure PHY_Registers_Tests is
begin
   declare
      R : Misc_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_Low := Bits_20'Last;
      pragma Assert (Encode (R) = 16#FFFFF#);
      R := Decode (16#FFFFF#);
      pragma Assert (R.Reserved_Low = Bits_20'Last);
      R := Decode (Unsigned_32'(0));
      R.Spare_20 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#100000#);
      R := Decode (16#100000#);
      pragma Assert (R.Spare_20 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Spare_21 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#200000#);
      R := Decode (16#200000#);
      pragma Assert (R.Spare_21 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Spare_22 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#400000#);
      R := Decode (16#400000#);
      pragma Assert (R.Spare_22 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Comp_Power_Down := Bits_1'Last;
      pragma Assert (Encode (R) = 16#800000#);
      R := Decode (16#800000#);
      pragma Assert (R.Comp_Power_Down = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.IO_To_DE := Bits_4'Last;
      pragma Assert (Encode (R) = 16#F000000#);
      R := Decode (16#F000000#);
      pragma Assert (R.IO_To_DE = Bits_4'Last);
      R := Decode (Unsigned_32'(0));
      R.DE_To_IO := Bits_4'Last;
      pragma Assert (Encode (R) = 16#F0000000#);
      R := Decode (16#F0000000#);
      pragma Assert (R.DE_To_IO = Bits_4'Last);
   end;
   declare
      R : TX_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.ODCC_Upper_Limit := Bits_5'Last;
      pragma Assert (Encode (R) = 16#1F#);
      R := Decode (16#1F#);
      pragma Assert (R.ODCC_Upper_Limit = Bits_5'Last);
      R := Decode (Unsigned_32'(0));
      R.IDCC_Therm_Low := Bits_3'Last;
      pragma Assert (Encode (R) = 16#E0#);
      R := Decode (16#E0#);
      pragma Assert (R.IDCC_Therm_Low = Bits_3'Last);
      R := Decode (Unsigned_32'(0));
      R.IDCC_Code := Bits_5'Last;
      pragma Assert (Encode (R) = 16#1F00#);
      R := Decode (16#1F00#);
      pragma Assert (R.IDCC_Code = Bits_5'Last);
      R := Decode (Unsigned_32'(0));
      R.IDCC_Therm_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#6000#);
      R := Decode (16#6000#);
      pragma Assert (R.IDCC_Therm_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_15 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#8000#);
      R := Decode (16#8000#);
      pragma Assert (R.Reserved_15 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.ODCC_Lower_Limit := Bits_5'Last;
      pragma Assert (Encode (R) = 16#1F0000#);
      R := Decode (16#1F0000#);
      pragma Assert (R.ODCC_Lower_Limit = Bits_5'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_21 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#200000#);
      R := Decode (16#200000#);
      pragma Assert (R.Reserved_21 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.ODCC_Fuse_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#400000#);
      R := Decode (16#400000#);
      pragma Assert (R.ODCC_Fuse_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.ODCC_Override_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#800000#);
      R := Decode (16#800000#);
      pragma Assert (R.ODCC_Override_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.ODCC_Override_Code := Bits_5'Last;
      pragma Assert (Encode (R) = 16#1F000000#);
      R := Decode (16#1F000000#);
      pragma Assert (R.ODCC_Override_Code = Bits_5'Last);
      R := Decode (Unsigned_32'(0));
      R.Clock_Divider := Bits_2'Last;
      pragma Assert (Encode (R) = 16#60000000#);
      R := Decode (16#60000000#);
      pragma Assert (R.Clock_Divider = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Clock_Select := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80000000#);
      R := Decode (16#80000000#);
      pragma Assert (R.Clock_Select = Bits_1'Last);
   end;
   declare
      R : PCS_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.Soft_Reset_N := Bits_1'Last;
      pragma Assert (Encode (R) = 16#1#);
      R := Decode (16#1#);
      pragma Assert (R.Soft_Reset_N = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Soft_Reset_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#2#);
      R := Decode (16#2#);
      pragma Assert (R.Soft_Reset_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Latency_Optimize := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C#);
      R := Decode (16#C#);
      pragma Assert (R.Latency_Optimize = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Deemphasis := Bits_1'Last;
      pragma Assert (Encode (R) = 16#10#);
      R := Decode (16#10#);
      pragma Assert (R.Deemphasis = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.FIFO_Reset_Override := Bits_1'Last;
      pragma Assert (Encode (R) = 16#20#);
      R := Decode (16#20#);
      pragma Assert (R.FIFO_Reset_Override = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.FIFO_Reset_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#40#);
      R := Decode (16#40#);
      pragma Assert (R.FIFO_Reset_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.TBC_Symbol_Clock := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80#);
      R := Decode (16#80#);
      pragma Assert (R.TBC_Symbol_Clock = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Clock_Request := Bits_2'Last;
      pragma Assert (Encode (R) = 16#300#);
      R := Decode (16#300#);
      pragma Assert (R.Clock_Request = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_10 := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C00#);
      R := Decode (16#C00#);
      pragma Assert (R.Reserved_10 = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.TX_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3000#);
      R := Decode (16#3000#);
      pragma Assert (R.TX_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_14 := Bits_3'Last;
      pragma Assert (Encode (R) = 16#1C000#);
      R := Decode (16#1C000#);
      pragma Assert (R.Reserved_14 = Bits_3'Last);
      R := Decode (Unsigned_32'(0));
      R.TX_Calibration_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#20000#);
      R := Decode (16#20000#);
      pragma Assert (R.TX_Calibration_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Calibration_Wake := Bits_1'Last;
      pragma Assert (Encode (R) = 16#40000#);
      R := Decode (16#40000#);
      pragma Assert (R.Calibration_Wake = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Calibration_Bypass := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80000#);
      R := Decode (16#80000#);
      pragma Assert (R.Calibration_Bypass = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.DCC_Mode := Bits_2'Last;
      pragma Assert (Encode (R) = 16#300000#);
      R := Decode (16#300000#);
      pragma Assert (R.DCC_Mode = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_22 := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C00000#);
      R := Decode (16#C00000#);
      pragma Assert (R.Reserved_22 = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Keeper_Bias := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3000000#);
      R := Decode (16#3000000#);
      pragma Assert (R.Keeper_Bias = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Keeper_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#4000000#);
      R := Decode (16#4000000#);
      pragma Assert (R.Keeper_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Power_Down_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#8000000#);
      R := Decode (16#8000000#);
      pragma Assert (R.Power_Down_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Keeper_In_PG := Bits_1'Last;
      pragma Assert (Encode (R) = 16#10000000#);
      R := Decode (16#10000000#);
      pragma Assert (R.Keeper_In_PG = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_29 := Bits_3'Last;
      pragma Assert (Encode (R) = 16#E0000000#);
      R := Decode (16#E0000000#);
      pragma Assert (R.Reserved_29 = Bits_3'Last);
   end;
   declare
      R : Comp0_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.Unspecified_ADLN_Low := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF#);
      R := Decode (16#FF#);
      pragma Assert (R.Unspecified_ADLN_Low = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.Periodic_Counter := Bits_12'Last;
      pragma Assert (Encode (R) = 16#FFF00#);
      R := Decode (16#FFF00#);
      pragma Assert (R.Periodic_Counter = Bits_12'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_20 := Bits_3'Last;
      pragma Assert (Encode (R) = 16#700000#);
      R := Decode (16#700000#);
      pragma Assert (R.Reserved_20 = Bits_3'Last);
      R := Decode (Unsigned_32'(0));
      R.Procmon_Clock := Bits_1'Last;
      pragma Assert (Encode (R) = 16#800000#);
      R := Decode (16#800000#);
      pragma Assert (R.Procmon_Clock = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Spare := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3000000#);
      R := Decode (16#3000000#);
      pragma Assert (R.Spare = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Drive_Switch_Control := Bits_1'Last;
      pragma Assert (Encode (R) = 16#4000000#);
      R := Decode (16#4000000#);
      pragma Assert (R.Drive_Switch_Control = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Drive_Switch_On := Bits_2'Last;
      pragma Assert (Encode (R) = 16#18000000#);
      R := Decode (16#18000000#);
      pragma Assert (R.Drive_Switch_On = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Slew_Control := Bits_2'Last;
      pragma Assert (Encode (R) = 16#60000000#);
      R := Decode (16#60000000#);
      pragma Assert (R.Slew_Control = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Initialized := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80000000#);
      R := Decode (16#80000000#);
      pragma Assert (R.Initialized = Bits_1'Last);
   end;
   declare
      R : Comp1_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.NLVT_Low := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3#);
      R := Decode (16#3#);
      pragma Assert (R.NLVT_Low = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.NLVT_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C#);
      R := Decode (16#C#);
      pragma Assert (R.NLVT_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.PLVT_Low := Bits_2'Last;
      pragma Assert (Encode (R) = 16#30#);
      R := Decode (16#30#);
      pragma Assert (R.PLVT_Low = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.PLVT_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C0#);
      R := Decode (16#C0#);
      pragma Assert (R.PLVT_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.NHVT_Low := Bits_2'Last;
      pragma Assert (Encode (R) = 16#300#);
      R := Decode (16#300#);
      pragma Assert (R.NHVT_Low = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.NHVT_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C00#);
      R := Decode (16#C00#);
      pragma Assert (R.NHVT_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.PHVT_Low := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3000#);
      R := Decode (16#3000#);
      pragma Assert (R.PHVT_Low = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.PHVT_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C000#);
      R := Decode (16#C000#);
      pragma Assert (R.PHVT_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.N_Low := Bits_2'Last;
      pragma Assert (Encode (R) = 16#30000#);
      R := Decode (16#30000#);
      pragma Assert (R.N_Low = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.N_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C0000#);
      R := Decode (16#C0000#);
      pragma Assert (R.N_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.P_Low := Bits_2'Last;
      pragma Assert (Encode (R) = 16#300000#);
      R := Decode (16#300000#);
      pragma Assert (R.P_Low = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.P_High := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C00000#);
      R := Decode (16#C00000#);
      pragma Assert (R.P_High = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Rcomp_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#1000000#);
      R := Decode (16#1000000#);
      pragma Assert (R.Rcomp_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Fcomp_Polarity := Bits_1'Last;
      pragma Assert (Encode (R) = 16#2000000#);
      R := Decode (16#2000000#);
      pragma Assert (R.Fcomp_Polarity = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Fcomp_Input := Bits_2'Last;
      pragma Assert (Encode (R) = 16#C000000#);
      R := Decode (16#C000000#);
      pragma Assert (R.Fcomp_Input = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Fcomp_Bias := Bits_1'Last;
      pragma Assert (Encode (R) = 16#10000000#);
      R := Decode (16#10000000#);
      pragma Assert (R.Fcomp_Bias = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Fcomp_Cap_Ratio := Bits_1'Last;
      pragma Assert (Encode (R) = 16#20000000#);
      R := Decode (16#20000000#);
      pragma Assert (R.Fcomp_Cap_Ratio = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Fcomp_Override := Bits_1'Last;
      pragma Assert (Encode (R) = 16#40000000#);
      R := Decode (16#40000000#);
      pragma Assert (R.Fcomp_Override = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.LDO_Bypass := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80000000#);
      R := Decode (16#80000000#);
      pragma Assert (R.LDO_Bypass = Bits_1'Last);
   end;
   declare
      R : Comp3_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.MIPI_Lpdn_Code := Bits_6'Last;
      pragma Assert (Encode (R) = 16#3F#);
      R := Decode (16#3F#);
      pragma Assert (R.MIPI_Lpdn_Code = Bits_6'Last);
      R := Decode (Unsigned_32'(0));
      R.Lpdn_Min := Bits_1'Last;
      pragma Assert (Encode (R) = 16#40#);
      R := Decode (16#40#);
      pragma Assert (R.Lpdn_Min = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Lpdn_Max := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80#);
      R := Decode (16#80#);
      pragma Assert (R.Lpdn_Max = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Icomp_Code := Bits_7'Last;
      pragma Assert (Encode (R) = 16#7F00#);
      R := Decode (16#7F00#);
      pragma Assert (R.Icomp_Code = Bits_7'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_15 := Bits_4'Last;
      pragma Assert (Encode (R) = 16#78000#);
      R := Decode (16#78000#);
      pragma Assert (R.Reserved_15 = Bits_4'Last);
      R := Decode (Unsigned_32'(0));
      R.Icomp_Min := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80000#);
      R := Decode (16#80000#);
      pragma Assert (R.Icomp_Min = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Icomp_Max := Bits_1'Last;
      pragma Assert (Encode (R) = 16#100000#);
      R := Decode (16#100000#);
      pragma Assert (R.Icomp_Max = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Procmon_Done := Bits_1'Last;
      pragma Assert (Encode (R) = 16#200000#);
      R := Decode (16#200000#);
      pragma Assert (R.Procmon_Done = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.First_Comp_Done := Bits_1'Last;
      pragma Assert (Encode (R) = 16#400000#);
      R := Decode (16#400000#);
      pragma Assert (R.First_Comp_Done = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.PLL_Power_Ack := Bits_1'Last;
      pragma Assert (Encode (R) = 16#800000#);
      R := Decode (16#800000#);
      pragma Assert (R.PLL_Power_Ack = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Voltage_Info := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3000000#);
      R := Decode (16#3000000#);
      pragma Assert (R.Voltage_Info = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Process_Info := Bits_3'Last;
      pragma Assert (Encode (R) = 16#1C000000#);
      R := Decode (16#1C000000#);
      pragma Assert (R.Process_Info = Bits_3'Last);
      R := Decode (Unsigned_32'(0));
      R.Unspecified_ADLN_High := Bits_3'Last;
      pragma Assert (Encode (R) = 16#E0000000#);
      R := Decode (16#E0000000#);
      pragma Assert (R.Unspecified_ADLN_High = Bits_3'Last);
   end;
   declare
      R : Comp8_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_Low := Bits_14'Last;
      pragma Assert (Encode (R) = 16#3FFF#);
      R := Decode (16#3FFF#);
      pragma Assert (R.Reserved_Low = Bits_14'Last);
      R := Decode (Unsigned_32'(0));
      R.Disable_Periodic_Comp := Bits_1'Last;
      pragma Assert (Encode (R) = 16#4000#);
      R := Decode (16#4000#);
      pragma Assert (R.Disable_Periodic_Comp = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_15 := Bits_9'Last;
      pragma Assert (Encode (R) = 16#FF8000#);
      R := Decode (16#FF8000#);
      pragma Assert (R.Reserved_15 = Bits_9'Last);
      R := Decode (Unsigned_32'(0));
      R.Reference_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#1000000#);
      R := Decode (16#1000000#);
      pragma Assert (R.Reference_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_25 := Bits_7'Last;
      pragma Assert (Encode (R) = 16#FE000000#);
      R := Decode (16#FE000000#);
      pragma Assert (R.Reserved_25 = Bits_7'Last);
   end;
   declare
      R : Comp9_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.P_High := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF#);
      R := Decode (16#FF#);
      pragma Assert (R.P_High = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.P_Low := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF00#);
      R := Decode (16#FF00#);
      pragma Assert (R.P_Low = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.N_High := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF0000#);
      R := Decode (16#FF0000#);
      pragma Assert (R.N_High = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.N_Low := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF000000#);
      R := Decode (16#FF000000#);
      pragma Assert (R.N_Low = Bits_8'Last);
   end;
   declare
      R : Comp10_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.PLVT_High := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF#);
      R := Decode (16#FF#);
      pragma Assert (R.PLVT_High = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.PLVT_Low := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF00#);
      R := Decode (16#FF00#);
      pragma Assert (R.PLVT_Low = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.NLVT_High := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF0000#);
      R := Decode (16#FF0000#);
      pragma Assert (R.NLVT_High = Bits_8'Last);
      R := Decode (Unsigned_32'(0));
      R.NLVT_Low := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF000000#);
      R := Decode (16#FF000000#);
      pragma Assert (R.NLVT_Low = Bits_8'Last);
   end;
   declare
      R : CL_Register;
   begin
      for Bit in 0 .. 31 loop
         R := Decode (Shift_Left (Unsigned_32'(1), Bit));
         pragma Assert (Encode (R) = Shift_Left (Unsigned_32'(1), Bit));
      end loop;
      R := Decode (Unsigned_32'Last);
      pragma Assert (Encode (R) = Unsigned_32'Last);
      R := Decode (Unsigned_32'(0));
      R.Suspend_Clock := Bits_2'Last;
      pragma Assert (Encode (R) = 16#3#);
      R := Decode (16#3#);
      pragma Assert (R.Suspend_Clock = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Power_Ack_Override := Bits_1'Last;
      pragma Assert (Encode (R) = 16#4#);
      R := Decode (16#4#);
      pragma Assert (R.Power_Ack_Override = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.CRI_Clock_Select := Bits_1'Last;
      pragma Assert (Encode (R) = 16#8#);
      R := Decode (16#8#);
      pragma Assert (R.CRI_Clock_Select = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Power_Down_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#10#);
      R := Decode (16#10#);
      pragma Assert (R.Power_Down_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Stagger_Disable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#20#);
      R := Decode (16#20#);
      pragma Assert (R.Stagger_Disable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Port_Stagger := Bits_1'Last;
      pragma Assert (Encode (R) = 16#40#);
      R := Decode (16#40#);
      pragma Assert (R.Port_Stagger = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_7 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#80#);
      R := Decode (16#80#);
      pragma Assert (R.Reserved_7 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Broadcast_Enable := Bits_1'Last;
      pragma Assert (Encode (R) = 16#100#);
      R := Decode (16#100#);
      pragma Assert (R.Broadcast_Enable = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.IOSF_Divider := Bits_3'Last;
      pragma Assert (Encode (R) = 16#E00#);
      R := Decode (16#E00#);
      pragma Assert (R.IOSF_Divider = Bits_3'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_12 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#1000#);
      R := Decode (16#1000#);
      pragma Assert (R.Reserved_12 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.IOSF_PD_Count := Bits_2'Last;
      pragma Assert (Encode (R) = 16#6000#);
      R := Decode (16#6000#);
      pragma Assert (R.IOSF_PD_Count = Bits_2'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_15 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#8000#);
      R := Decode (16#8000#);
      pragma Assert (R.Reserved_15 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.CRI_Max := Bits_4'Last;
      pragma Assert (Encode (R) = 16#F0000#);
      R := Decode (16#F0000#);
      pragma Assert (R.CRI_Max = Bits_4'Last);
      R := Decode (Unsigned_32'(0));
      R.Fuse_Repull := Bits_1'Last;
      pragma Assert (Encode (R) = 16#100000#);
      R := Decode (16#100000#);
      pragma Assert (R.Fuse_Repull = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Fuse_Override := Bits_1'Last;
      pragma Assert (Encode (R) = 16#200000#);
      R := Decode (16#200000#);
      pragma Assert (R.Fuse_Override = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Fuse_Reset := Bits_1'Last;
      pragma Assert (Encode (R) = 16#400000#);
      R := Decode (16#400000#);
      pragma Assert (R.Fuse_Reset = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Reserved_23 := Bits_1'Last;
      pragma Assert (Encode (R) = 16#800000#);
      R := Decode (16#800000#);
      pragma Assert (R.Reserved_23 = Bits_1'Last);
      R := Decode (Unsigned_32'(0));
      R.Force_Control := Bits_8'Last;
      pragma Assert (Encode (R) = 16#FF000000#);
      R := Decode (16#FF000000#);
      pragma Assert (R.Force_Control = Bits_8'Last);
   end;
   Ada.Text_IO.Put_Line ("PHY register representation: ten layouts, 112 field boundaries, single-bit round trips PASS");
end PHY_Registers_Tests;
