with Ada.Text_IO;
with Interfaces; use Interfaces;
with System.Storage_Elements; use System.Storage_Elements;
with Intel_GPU_Table_References;
procedure Table_Reference_Store_Tests is
   package R is new Intel_GPU_Table_References (4096);
   Object : R.Map;
   type Bytes is array (Positive range <>) of Unsigned_8;
   Memory : aliased Bytes (1 .. 69632) := [others => 16#AC#] with Alignment => 4096;
   Saved : Bytes (Memory'Range);
   Base : constant Unsigned_64 := Unsigned_64 (To_Integer (Memory'Address));
   OK : Boolean;
begin
   pragma Assert (R.Capacity (Object) = 4 and R.Generation (Object) = 1);
   pragma Assert (Object'Size / 8 < 4096);
   R.Put (Object, 1, 4, 65, OK); pragma Assert (OK);
   R.Put (Object, 1, 5, 97, OK); pragma Assert (not OK);
   R.Put (Object, 0, 1, 99, OK); pragma Assert (not OK);
   R.Put (Object, 1, 0, 99, OK); pragma Assert (not OK);
   R.Put (Object, 1, 1, 0, OK); pragma Assert (not OK);
   pragma Assert (R.Get (Object, 1, 4) = 65 and R.Get (Object, 1, 5) = 0);
   R.Extend (Object, Base, 4096, OK); pragma Assert (OK and R.Capacity (Object) > 64);
   pragma Assert (R.Get (Object, 1, 4) = 65 and R.Generation (Object) = 1);
   R.Put (Object, 1, 65, 5001, OK); pragma Assert (OK);
   R.Extend (Object, Base, R.Metadata_Bytes, OK);
   pragma Assert (OK and R.Capacity (Object) = 4096);
   pragma Assert (R.Get (Object, 1, 65) = 5001);
   R.Put (Object, 1, 4096, Natural'Last, OK); pragma Assert (OK);
   R.Put (Object, 1, 4097, 1, OK); pragma Assert (not OK);
   pragma Assert (R.Get (Object, 1, 4097) = 0);
   Saved := Memory;
   R.Extend (Object, Base + 4096, R.Metadata_Bytes, OK); pragma Assert (not OK);
   R.Extend (Object, Base, R.Metadata_Bytes + 4096, OK); pragma Assert (not OK);
   R.Reopen (Object, 2, 3, OK); pragma Assert (not OK);
   R.Reopen (Object, 1, 1, OK); pragma Assert (not OK);
   R.Reopen (Object, 1, 3, OK); pragma Assert (not OK);
   pragma Assert (Memory = Saved and R.Get (Object, 1, 4096) = Natural'Last);
   R.Reopen (Object, 1, 2, OK); pragma Assert (OK and Memory = Saved);
   pragma Assert (R.Capacity (Object) = 4096 and R.Generation (Object) = 2);
   for P in 1 .. 4096 loop
      pragma Assert (R.Get (Object, 1, P) = 0 and R.Get (Object, 2, P) = 0);
   end loop;
   R.Put (Object, 1, 65, 88, OK); pragma Assert (not OK and Memory = Saved);
   R.Put (Object, 2, 65, 9001, OK); pragma Assert (OK);
   pragma Assert (R.Get (Object, 2, 65) = 9001 and R.Get (Object, 1, 65) = 0);
   R.Reopen (Object, 1, 2, OK); pragma Assert (not OK);
   pragma Assert (for all I in Natural (R.Metadata_Bytes) + 1 .. Memory'Last => Memory (I) = 16#AC#);
   Ada.Text_IO.Put_Line ("Table reference store PASS: bootstrap4->4096, stable IDs distinct from ordinals, checked capacity/generation, constant-work reset without clearing/releasing backing");
end Table_Reference_Store_Tests;
